-- ============================================================================
-- بيانات العمليات الحقيقية — مُولَّدة آلياً. لا تعدّل هذا الملف يدوياً.
-- المصدر: src/data/ops/*.json
-- التوليد: python3 scripts/ops/gen_seed.py
-- المحتوى: 53 صنف · 80 مكوّن · 457 سطر وصفة · 14 يوم دوران
--
-- idempotent: تنفيذه مرة ثانية يحدّث القيم ولا يكرّرها.
-- ملاحظة: ما يلمس بوابات الجودة ولا خطة الإنتاج — هذي يدخلها الفريق.
-- ============================================================================

begin;

-- 80 مكوّن
insert into ops_ingredients (key, name, name_en, kcal, protein, carb, fat, fiber, price, allergen_text, source, flags, hidden, sort_order) values
  ('chicken_breast', 'صدر دجاج بدون جلد (نيء)', 'Chicken breast, skinless, raw', 120, 22.5, 0, 2.6, 0, 24, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 0),
  ('chicken_thigh', 'فخذ دجاج بدون عظم/جلد (نيء)', 'Chicken thigh, boneless skinless, raw', 121, 19.7, 0, 4.1, 0, 20, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 1),
  ('beef_mince', 'لحم بقر مفروم 95% قليل الدهن (نيء)', 'Beef mince 95% lean, raw', 137, 21.4, 0, 5, 0, 52, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 2),
  ('beef_sirloin', 'سيرلوين بقري منقّى من الدهن (نيء)', 'Beef top sirloin, trimmed, raw', 135, 21.5, 0, 4.5, 0, 62, '', 'USDA FDC (تقريبي من الذاكرة). تقريبي', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 3),
  ('lamb_leg', 'لحم غنم (فخذ) قليل الدهن (نيء)', 'Lamb leg, lean, raw', 137, 20.5, 0, 5.5, 0, 68, '', 'USDA FDC (تقريبي من الذاكرة). تقريبي', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 4),
  ('hammour', 'هامور فيليه (نيء)', 'Grouper fillet, raw', 92, 19.4, 0, 1, 0, 70, 'سمك', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": true, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 5),
  ('white_fish', 'سمك أبيض فيليه - سي باص/دنيس (نيء)', 'White fish fillet (sea bass/bream), raw', 97, 18.4, 0, 2, 0, 48, 'سمك', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": true, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 6),
  ('salmon', 'سلمون أطلسي فيليه (نيء)', 'Atlantic salmon, raw', 208, 20.4, 0, 13.4, 0, 62, 'سمك', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": true, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 7),
  ('shrimp', 'ربيان مقشّر منزوع العرق (نيء)', 'Shrimp, peeled, raw', 85, 20.1, 0.2, 0.5, 0, 55, 'قشريات', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": true, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 8),
  ('tuna', 'تونة معلبة بالماء (مصفّاة)', 'Tuna in water, drained', 116, 25.5, 0, 0.8, 0, 52, 'سمك', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": true, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 9),
  ('turkey_slices', 'شرائح صدر ديك رومي', 'Turkey breast slices (deli)', 105, 17, 3, 2, 0, 60, '', 'USDA FDC (تقريبي من الذاكرة). تقريبي - راجع الملصق', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 10),
  ('egg_whole', 'بيض كامل', 'Whole egg', 143, 12.6, 0.7, 9.5, 0, 12, 'بيض', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": true, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 11),
  ('egg_white', 'بياض بيض', 'Egg white', 52, 10.9, 0.7, 0.2, 0, 14, 'بيض', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": true, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 12),
  ('greek_yogurt', 'زبادي يوناني 0%', 'Greek yogurt, nonfat', 59, 10.2, 3.6, 0.4, 0, 16, 'ألبان', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": true, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 13),
  ('yogurt_low', 'لبن زبادي قليل الدسم', 'Plain lowfat yogurt', 63, 5.3, 7, 1.6, 0, 9, 'ألبان', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": true, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 14),
  ('milk_low', 'حليب قليل الدسم 1%', 'Milk 1%', 42, 3.4, 5, 1, 0, 6, 'ألبان', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": true, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 15),
  ('parmesan', 'بارميزان', 'Parmesan', 431, 38.5, 4.1, 28.6, 0, 85, 'ألبان', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": true, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 16),
  ('mozzarella', 'موزاريلا قليلة الدسم', 'Mozzarella part-skim', 254, 24.3, 2.8, 15.9, 0, 40, 'ألبان', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": true, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 17),
  ('feta', 'جبن فيتا', 'Feta', 264, 14.2, 4.1, 21.3, 0, 38, 'ألبان', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": true, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 18),
  ('ghee', 'سمن', 'Ghee', 876, 0.3, 0, 99.5, 0, 38, 'ألبان', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": true, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 19),
  ('olive_oil', 'زيت زيتون', 'Olive oil', 884, 0, 0, 100, 0, 32, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 20),
  ('coconut_milk', 'حليب جوز الهند (معلّب)', 'Coconut milk, canned', 197, 2, 2.8, 21.3, 0, 18, '', 'USDA FDC (تقريبي من الذاكرة). يختلف حسب الماركة - راجع الملصق', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 21),
  ('tahini', 'طحينة', 'Tahini', 595, 17, 21.2, 53.8, 9.3, 36, 'سمسم', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": true, "celery": false}'::jsonb, '', 22),
  ('almonds', 'لوز', 'Almonds', 579, 21.2, 21.6, 49.9, 12.5, 60, 'مكسرات', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": true, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 23),
  ('peanut_butter', 'زبدة فول سوداني طبيعية', 'Natural peanut butter', 588, 25, 20, 50, 6, 28, 'فول سوداني', 'USDA FDC (تقريبي من الذاكرة). تقريبي', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": true, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 24),
  ('pumpkin_seeds', 'بذور يقطين', 'Pumpkin seeds', 559, 30.2, 10.7, 49.1, 6, 50, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 25),
  ('chia', 'بذور شيا', 'Chia seeds', 486, 16.5, 42.1, 30.7, 34.4, 40, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 26),
  ('sesame', 'سمسم', 'Sesame seeds', 573, 17.7, 23.5, 49.7, 11.8, 30, 'سمسم', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": true, "celery": false}'::jsonb, '', 27),
  ('basmati', 'أرز بسمتي/أبيض (نيء)', 'White long-grain rice, raw', 365, 7.1, 80, 0.7, 1.3, 10, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 28),
  ('brown_rice', 'أرز بني (نيء)', 'Brown rice, raw', 370, 7.9, 77.2, 2.9, 3.5, 12, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 29),
  ('quinoa', 'كينوا (نيئة)', 'Quinoa, raw', 368, 14.1, 64.2, 6.1, 7, 24, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 30),
  ('bulgur', 'برغل (نيء)', 'Bulgur, raw', 342, 12.3, 75.9, 1.3, 12.5, 9, 'غلوتين (قمح)', 'USDA FDC (مقرّب)', '{"gluten": true, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 31),
  ('jareesh', 'جريش - قمح مجروش (جاف)', 'Cracked wheat (jareesh), dry', 327, 12.6, 71.2, 1.5, 12.2, 9, 'غلوتين (قمح)', 'USDA FDC (تقريبي من الذاكرة). تقريبي - راجع الملصق', '{"gluten": true, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 32),
  ('ww_pasta', 'باستا حبوب كاملة (جافة)', 'Whole-wheat pasta, dry', 350, 14, 72, 2.8, 8, 12, 'غلوتين (قمح)', 'USDA FDC (تقريبي من الذاكرة). تقريبي - راجع الملصق', '{"gluten": true, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 33),
  ('vermicelli', 'شعيرية (جافة)', 'Vermicelli, dry', 371, 13, 74.7, 1.5, 3.2, 8, 'غلوتين (قمح)', 'USDA FDC (مقرّب)', '{"gluten": true, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 34),
  ('oats', 'شوفان', 'Rolled oats', 379, 13.2, 67.7, 6.5, 10.1, 12, 'غلوتين (شوفان — احتمال تلوث قمح)', 'USDA FDC (تقريبي من الذاكرة). قد يحوي آثار غلوتين', '{"gluten": true, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, 'تلوث قمح', 35),
  ('potato', 'بطاطس (نيئة)', 'Potato, raw', 77, 2, 17.5, 0.1, 2.2, 4, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 36),
  ('sweet_potato', 'بطاطا حلوة (نيئة)', 'Sweet potato, raw', 86, 1.6, 20.1, 0.1, 3, 6, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 37),
  ('ww_bread', 'خبز حبوب كاملة', 'Whole-wheat bread', 250, 12, 43, 3.5, 7, 18, 'غلوتين (قمح)', 'USDA FDC (تقريبي من الذاكرة). تقريبي - راجع الملصق', '{"gluten": true, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 38),
  ('ww_flour', 'دقيق قمح كامل', 'Whole-wheat flour', 340, 13.2, 72, 2.5, 10.7, 7, 'غلوتين (قمح)', 'USDA FDC (مقرّب)', '{"gluten": true, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 39),
  ('millet_flour', 'دقيق دخن', 'Millet flour', 378, 11, 72.8, 4.2, 8.5, 12, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, 'تلوث غلوتين', 40),
  ('chickpea_cooked', 'حمص مسلوق', 'Chickpeas, cooked', 164, 8.9, 27.4, 2.6, 7.6, 8, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 41),
  ('lentil_dry', 'عدس (جاف)', 'Lentils, dry', 352, 24.6, 63.4, 1.1, 10.7, 10, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 42),
  ('fava_cooked', 'فول مدمس (مطبوخ)', 'Fava beans, cooked', 110, 7.6, 19.7, 0.4, 5.4, 7, '', 'USDA FDC (تقريبي من الذاكرة). المعلّب التجاري قد يختلف', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 43),
  ('edamame', 'إدامامي (مقشّر مجمّد)', 'Edamame, shelled', 121, 11.9, 8.9, 5.2, 5.2, 22, 'صويا', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": true, "sesame": false, "celery": false}'::jsonb, '', 44),
  ('black_beans', 'فاصوليا سوداء مطبوخة', 'Black beans, cooked', 132, 8.9, 23.7, 0.5, 8.7, 8, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 45),
  ('tomato', 'طماطم', 'Tomato', 18, 0.9, 3.9, 0.2, 1.2, 5, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 46),
  ('onion', 'بصل', 'Onion', 40, 1.1, 9.3, 0.1, 1.7, 3, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 47),
  ('garlic', 'ثوم', 'Garlic', 149, 6.4, 33.1, 0.5, 2.1, 18, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 48),
  ('bell_pepper', 'فلفل ألوان', 'Bell pepper', 31, 1, 6, 0.3, 2.1, 10, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 49),
  ('cucumber', 'خيار', 'Cucumber', 15, 0.7, 3.6, 0.1, 0.5, 4, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 50),
  ('carrot', 'جزر', 'Carrot', 41, 0.9, 9.6, 0.2, 2.8, 4, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 51),
  ('broccoli', 'بروكلي', 'Broccoli', 34, 2.8, 6.6, 0.4, 2.6, 9, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 52),
  ('zucchini', 'كوسا', 'Zucchini', 17, 1.2, 3.1, 0.3, 1, 6, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 53),
  ('spinach', 'سبانخ', 'Spinach', 23, 2.9, 3.6, 0.4, 2.2, 14, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 54),
  ('mushroom', 'مشروم', 'Mushrooms', 22, 3.1, 3.3, 0.3, 1, 18, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 55),
  ('cauliflower', 'قرنبيط', 'Cauliflower', 25, 1.9, 5, 0.3, 2, 7, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 56),
  ('green_beans', 'فاصوليا خضراء', 'Green beans', 31, 1.8, 7, 0.2, 2.7, 9, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 57),
  ('romaine', 'خس روماني', 'Romaine lettuce', 17, 1.2, 3.3, 0.3, 2.1, 9, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 58),
  ('arugula', 'جرجير', 'Arugula', 25, 2.6, 3.7, 0.7, 1.6, 20, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 59),
  ('pumpkin', 'يقطين', 'Pumpkin', 26, 1, 6.5, 0.1, 0.5, 5, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 60),
  ('cabbage', 'ملفوف', 'Cabbage', 25, 1.3, 5.8, 0.1, 2.5, 3, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 61),
  ('celery', 'كرفس', 'Celery', 14, 0.7, 3, 0.2, 1.6, 6, 'كرفس', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": true}'::jsonb, '', 62),
  ('corn', 'ذرة حلوة', 'Sweet corn', 86, 3.3, 19, 1.2, 2.7, 8, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 63),
  ('peas', 'بازلاء خضراء', 'Green peas', 81, 5.4, 14.5, 0.4, 5.7, 8, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 64),
  ('avocado', 'أفوكادو', 'Avocado', 160, 2, 8.5, 14.7, 6.7, 22, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 65),
  ('olives', 'زيتون', 'Olives', 115, 0.8, 6.3, 10.7, 3.2, 24, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 66),
  ('lemon_juice', 'عصير ليمون', 'Lemon juice', 22, 0.4, 6.9, 0.2, 0.3, 8, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 67),
  ('ginger', 'زنجبيل طازج', 'Ginger', 80, 1.8, 17.8, 0.8, 2, 14, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 68),
  ('herbs', 'أعشاب طازجة (بقدونس/كزبرة/شبت/ريحان)', 'Fresh herbs (parsley basis)', 36, 3, 6.3, 0.8, 3.3, 15, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 69),
  ('tomato_crushed', 'طماطم مهروسة معلّبة', 'Crushed tomatoes, canned', 32, 1.6, 7.3, 0.3, 1.9, 8, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 70),
  ('tomato_paste', 'معجون طماطم', 'Tomato paste', 82, 4.3, 18.9, 0.5, 4.1, 14, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 71),
  ('dates', 'تمر (خلاص/مجدول) منزوع النوى', 'Dates, pitted', 277, 1.8, 75, 0.2, 6.7, 30, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 72),
  ('berries', 'توت مشكّل', 'Mixed berries', 57, 0.7, 14.5, 0.3, 2.4, 45, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 73),
  ('cocoa', 'كاكاو غير محلّى', 'Cocoa powder, unsweetened', 228, 19.6, 57.9, 13.7, 33.2, 40, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 74),
  ('honey', 'عسل', 'Honey', 304, 0.3, 82.4, 0, 0.2, 40, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, '', 75),
  ('soy_sauce', 'صويا صوص', 'Soy sauce', 53, 8.1, 4.9, 0.6, 0.8, 12, 'غلوتين (قمح)، صويا', 'USDA FDC (تقريبي من الذاكرة). عالي الصوديوم - استخدم قليل الصوديوم لقسم الصوديوم المنخفض', '{"gluten": true, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": true, "sesame": false, "celery": false}'::jsonb, '', 76),
  ('balsamic', 'خل بلسمك', 'Balsamic vinegar', 88, 0.5, 17, 0, 0, 20, '', 'USDA FDC (مقرّب)', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, 'كبريتيت', 77),
  ('spice', 'خليط بهارات جافة (تقديري)', 'Dry spice blend (typical)', 300, 11, 55, 10, 25, 60, '', 'USDA FDC (تقريبي من الذاكرة). تقديري: يختلف حسب الخلطة', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, 'خردل / كرفس / سمسم', 78),
  ('chicken_stock', 'مرق دجاج قليل الصوديوم', 'Chicken stock, low sodium', 7, 1, 0.5, 0.2, 0, 6, '', 'USDA FDC (تقريبي من الذاكرة). تقريبي', '{"gluten": false, "dairy": false, "egg": false, "fish": false, "shellfish": false, "nuts": false, "peanut": false, "soy": false, "sesame": false, "celery": false}'::jsonb, 'كرفس / غلوتين / صويا', 79)
on conflict (key) do update set
  name = excluded.name, name_en = excluded.name_en, kcal = excluded.kcal,
  protein = excluded.protein, carb = excluded.carb, fat = excluded.fat,
  fiber = excluded.fiber, price = excluded.price,
  allergen_text = excluded.allergen_text, source = excluded.source,
  flags = excluded.flags, hidden = excluded.hidden, sort_order = excluded.sort_order;

-- 53 صنف
insert into ops_menu_items (id, section, category, name, name_en, cuisine, identity, shelf_life_h, reheat, ops_note, method, eng_group, sort_order) values
  ('C01', 'رئيسي', 'دجاج', 'كبسة دجاج', 'Chicken Kabsa', 'سعودي', 'خليجي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'يُتبَّل الدجاج 4–12 س بالبهارات والليمون الأسود ثم يُسلق في المرق 15 د حتى 74°م ويُحمَّر 6 د بالفرن 220°م. يُحمَّر البصل والثوم بقدر الزيت، ثم الطماطم والمعجون والبهارات، ويُضاف الأرز المنقوع 20 د والمرق (1:1.5) ويُطهى مغطّى 18 د. الأرز يُبرَّد فوراً (انظر ورقة التشغيل).', 'رئيسي-دجاج', 0),
  ('C02', 'رئيسي', 'دجاج', 'مجبوس دجاج', 'Chicken Majboos', 'كويتي/قطري', 'خليجي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'يُحمَّر البصل حتى يصير ذهبياً ثم تُضاف الطماطم والبهارات (هيل، دارسين، ورق لوري، ليمون أسود) ويُضاف الدجاج المسلوق والمرق والأرز ويُطهى مغطّى 18 د على نار هادئة. عصرة ليمون عند الإغلاق.', 'رئيسي-دجاج', 1),
  ('C03', 'رئيسي', 'دجاج', 'شاورما دجاج بول', 'Chicken Shawarma Bowl', 'عربي', 'عربي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'صدر وفخذ دجاج يُتبَّلان 8–24 س بالزبادي والليمون وبهارات الشاورما ثم يُشويان على حرارة عالية (230°م) ويُقطَّعان رفيعاً. يُقدَّم مع أرز وخضار طازجة وصلصة ثوم لايت (زبادي + ليمون + ثوم).', 'رئيسي-دجاج', 2),
  ('C04', 'رئيسي', 'دجاج', 'شيش طاووق بأرز بالشعيرية', 'Shish Tawook with Vermicelli Rice', 'شامي/خليجي', 'عربي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'مكعبات الدجاج في مخلل الزبادي والثوم والليمون ومعجون الطماطم 6–12 س، تُشوى بالفرن على 230°م أو مشواة حتى 74°م. الأرز يُحمَّص فيه الشعيرية قبل الطهي. يُقدَّم مع فلفل وبصل مشويين.', 'رئيسي-دجاج', 3),
  ('C05', 'رئيسي', 'دجاج', 'دجاج تكا مسالا خفيف', 'Chicken Tikka Masala Lite', 'هندي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'الدجاج في زبادي يوناني وبهارات تكا 6 س ثم يُشوى. صلصة المسالا: بصل وثوم وزنجبيل مع طماطم مهروسة وبهارات وقليل من حليب جوز الهند (بدل الكريمة) وتُغلى 12 د. يُقدَّم مع أرز وقرنبيط مشوي.', 'رئيسي-دجاج', 4),
  ('C06', 'رئيسي', 'دجاج', 'برياني دجاج نظيف', 'Clean Chicken Biryani', 'هندي/خليجي', 'خليجي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'الدجاج في زبادي يوناني وبهارات برياني 8 س. يُحمَّر البصل، يُطهى الدجاج مع الطماطم، ثم تُرصّ الطبقات مع الأرز نصف المسلوق (70%) وتُغلق بإحكام وتُنضج على بخار 20 د. بدون قلي البصل بالزيت الغزير (يُشوى بالفرن).', 'رئيسي-دجاج', 5),
  ('C07', 'رئيسي', 'دجاج', 'دجاج تيرياكي بول', 'Teriyaki Chicken Bowl', 'ياباني/آسيوي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'صلصة التيرياكي: صويا + عسل + ثوم + زنجبيل تُختزل 5 د. يُشوى الدجاج ثم يُطلى بالصلصة آخر دقيقتين. بروكلي وجزر على البخار (قوامهما متماسك)، أرز بني، وسمسم للتقديم.', 'رئيسي-دجاج', 6),
  ('C08', 'رئيسي', 'دجاج', 'فاهيتا دجاج بول', 'Chicken Fajita Bowl', 'مكسيكي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'شرائح الدجاج في خلطة فاهيتا وليمون تُحمَّر على حرارة عالية مع الفلفل والبصل. أرز بني وفاصوليا سوداء. كريمة حامضة خفيفة (زبادي يوناني) وأفوكادو مهروس منفصل.', 'رئيسي-دجاج', 7),
  ('C09', 'رئيسي', 'دجاج', 'دجاج بالليمون والأعشاب', 'Lemon-Herb Chicken', 'متوسطي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'الدجاج في ليمون وثوم وأعشاب وقليل من زيت الزيتون 4–12 س، يُشوى 200°م حتى 74°م. بطاطس مكعبات مشوية بالفرن مع كوسا وفاصوليا خضراء.', 'رئيسي-دجاج', 8),
  ('C10', 'رئيسي', 'دجاج', 'دجاج كاتشياتوري', 'Chicken Cacciatore', 'إيطالي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'بديل الفريدو: صلصة الطماطم تتحمّل إعادة التسخين أفضل من الكريمة.', 'الدجاج يُحمَّر ثم يُطهى 25 د في صلصة طماطم وفلفل ومشروم وزيتون. صلصة الطماطم تتحمّل التبريد وإعادة التسخين أفضل بكثير من صلصات الكريمة (بديل الفريدو). المعكرونة حبوب كاملة تُسلق al dente وتُبرَّد بالماء البارد وتُخلط بقليل زيت.', 'رئيسي-دجاج', 9),
  ('C11', 'رئيسي', 'دجاج', 'دجاج باربكيو بالدبس', 'BBQ Chicken Plate', 'أمريكي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'صلصة باربكيو منزلية بلا سكر مكرر: معجون طماطم + عسل + خل بلسمك + بهارات مدخّنة. يُشوى الدجاج ويُطلى آخر 5 د. بطاطا حلوة مشوية وذرة.', 'رئيسي-دجاج', 10),
  ('C12', 'رئيسي', 'دجاج', 'جريش بالدجاج', 'Chicken Jareesh', 'سعودي (نجدي)', 'خليجي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'يُدفَّأ اللبن تدريجياً لتفادي التخثر.', 'يُنقع الجريش ليلة ثم يُطهى في المرق مع الدجاج المسلوق 45–60 د حتى يتماسك، ثم يُضاف اللبن (يُدفَّأ تدريجياً لتفادي التخثر) ويُخفق. توليفة بصل مكرمل وقطرة سمن فوقه.', 'رئيسي-دجاج', 11),
  ('M01', 'رئيسي', 'لحم', 'مندي لحم', 'Lamb Mandi', 'سعودي/يمني', 'خليجي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'أرز مطبوخ: تبريد صدمة ≤ 90 د (خطر Bacillus cereus). لحم الغنم: تكلفة عالية — راقب نسبة التكلفة.', 'اللحم يُتبَّل ببهارات المندي ويُطهى ببطء 120–150°م حتى يصير طرياً (حوالي 2.5–3 س)، يُمرَّر على دخان الفحم دقيقتين لنكهة المندي بدون زيادة دهون. الأرز يُطهى بمرق اللحم. سلطة طماطم حارة منفصلة.', 'رئيسي-لحم', 12),
  ('M02', 'رئيسي', 'لحم', 'مقلقل لحم', 'Beef Muqalqal', 'سعودي', 'خليجي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'شرائح السيرلوين تُحمَّر سريعاً على حرارة عالية (دفعات صغيرة) ثم تُطهى مع طماطم وبصل وفلفل وثوم وبهارات 8 د. تُقدَّم مع أرز أبيض.', 'رئيسي-لحم', 13),
  ('M03', 'رئيسي', 'لحم', 'لازانيا لحم قليلة الدسم', 'Lean Beef Lasagna', 'إيطالي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'ممتاز للتبريد/التجميد وإعادة التسخين.', 'طبقات: صلصة لحم (مفروم 95% + طماطم مهروسة) + كوسا شرائح + سبانخ + بيشاميل خفيف (حليب 1% + دقيق قمح كامل) + موزاريلا وبارميزان. تُخبز 190°م 35 د ثم ترتاح 15 د قبل التقطيع. من أفضل الأطباق تحمّلاً للتبريد وإعادة التسخين.', 'رئيسي-لحم', 14),
  ('M04', 'رئيسي', 'لحم', 'بيف بروكلي', 'Beef & Broccoli', 'صيني', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'شرائح السيرلوين رفيعة تُتبَّل بالصويا والعسل والثوم والزنجبيل، تُحمَّر في دفعات على حرارة عالية، وتُضاف إلى بروكلي مسلوق نصف سلقة. أرز بني وسمسم.', 'رئيسي-لحم', 15),
  ('M05', 'رئيسي', 'لحم', 'برجر لحم نظيف بول', 'Clean Burger Bowl', 'أمريكي (فاست فود نظيف)', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'قرص برجر مفروم 95% (بدون خبز) يُشوى حتى 71°م. بطاطس ودجز مخبوزة بالفرن (بدون قلي). خس وطماطم وخيار مخلل وصلصة برجر: زبادي يوناني + معجون طماطم.', 'رئيسي-لحم', 16),
  ('M06', 'رئيسي', 'لحم', 'كفتة لحم بالطحينة', 'Beef Kofta with Tahini', 'شامي/خليجي', 'عربي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'كفتة من المفروم مع بصل وبقدونس وبهارات تُشوى على الشواية/الفرن 220°م حتى 71°م. برغل بالطماطم، سلطة خيار وطماطم، وصلصة الطحينة بالليمون منفصلة.', 'رئيسي-لحم', 17),
  ('F01', 'رئيسي', 'سمك', 'صيادية هامور', 'Hammour Sayadiya', 'خليجي', 'خليجي', 48, 'بخار/ميكروويف على قوة متوسطة 2 د مغطّى (74°م في المركز) - لا تسخّن أكثر', 'أرز مطبوخ: تبريد صدمة ≤ 90 د (خطر Bacillus cereus). هامور: من أعلى الأصناف تكلفة — للنسخة الاقتصادية استبدله بسي باص/دنيس.', 'الفيليه يُتبَّل بالكمون والكركم والليمون ويُشوى 200°م 8–10 د حتى 63°م. أرز الصيادية: بصل مكرمل ببطء مع بهارات السمك. يُوضع السمك فوق الأرز بعد التبريد منفصلاً لتفادي جفافه. بديل أوفر: سي باص/دنيس.', 'رئيسي-بحري', 18),
  ('F02', 'رئيسي', 'ربيان', 'مجبوس ربيان', 'Shrimp Majboos', 'خليجي', 'خليجي', 48, 'بخار/ميكروويف على قوة متوسطة 2 د مغطّى (74°م في المركز) - لا تسخّن أكثر', 'أرز مطبوخ: تبريد صدمة ≤ 90 د (خطر Bacillus cereus). الربيان لا يُسخَّن أكثر من 90 ث. يُعبَّأ فوق الأرز بعد التبريد.', 'الأرز يُطهى بصلصة المجبوس (بصل، طماطم، بهارات) كاملاً، والربيان يُطهى 90 ث فقط على النار العالية (حتى يصير معتماً 63°م) ويُبرَّد فوراً ويوضع فوق الأرز. التسخين النهائي ≤ 90 ث كي لا يصير مطاطياً.', 'رئيسي-بحري', 19),
  ('F03', 'رئيسي', 'سمك', 'سلمون مشوي بصلصة الليمون والشبت', 'Salmon Lemon-Dill', 'متوسطي', 'عالمي', 48, 'بخار/ميكروويف على قوة متوسطة 2 د مغطّى (74°م في المركز) - لا تسخّن أكثر', '', 'السلمون يُشوى 200°م 9–11 د حتى 63°م. صلصة: زبادي يوناني + ليمون + شبت + ثوم. كينوا وبروكلي وفاصوليا خضراء على البخار.', 'رئيسي-بحري', 20),
  ('F04', 'رئيسي', 'سمك', 'سمك بالكاري وحليب جوز الهند', 'Coconut Fish Curry', 'هندي', 'عالمي', 48, 'بخار/ميكروويف على قوة متوسطة 2 د مغطّى (74°م في المركز) - لا تسخّن أكثر', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'تُطهى صلصة الكاري (بصل، ثوم، زنجبيل، بهارات، طماطم، حليب جوز الهند) 12 د ثم يُضاف السمك مكعبات ويُطهى 5 د على نار هادئة حتى 63°م. سبانخ تُضاف في النهاية.', 'رئيسي-بحري', 21),
  ('F05', 'رئيسي', 'سمك', 'طاجن سمك بالطماطم والخضار', 'Fish Tagine', 'مغاربي/خليجي', 'عربي', 48, 'بخار/ميكروويف على قوة متوسطة 2 د مغطّى (74°م في المركز) - لا تسخّن أكثر', '', 'طبقات بطاطس ثم خضار (طماطم، فلفل، كوسا، بصل) بصلصة الطماطم والبهارات والكمون والليمون، ثم فيليه السمك. يُخبز مغطّى 190°م 30 د. الصلصة تحمي السمك من الجفاف عند التسخين.', 'رئيسي-بحري', 22),
  ('F06', 'رئيسي', 'ربيان', 'أرز مقلّي بالربيان والخضار', 'Shrimp Fried Rice', 'صيني/آسيوي', 'عالمي', 48, 'بخار/ميكروويف على قوة متوسطة 2 د مغطّى (74°م في المركز) - لا تسخّن أكثر', 'أرز مطبوخ: تبريد صدمة ≤ 90 د (خطر Bacillus cereus). الربيان لا يُسخَّن أكثر من 90 ث.', 'أرز بني مبرَّد من اليوم السابق (يُقلى أفضل) مع جزر وبازلاء وملفوف وبيض. الربيان 90 ث فقط ثم يُضاف. صويا قليل ويُنهى بالسمسم.', 'رئيسي-بحري', 23),
  ('B01', 'فطور', 'فطور', 'شكشوكة بالخضار مع خبز حبوب', 'Veggie Shakshuka', 'عربي', 'عربي', 48, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'صلصة طماطم وفلفل وبصل وسبانخ تُطهى 12 د، ثم يُكسر البيض فوقها ويُغطى حتى ينضج (صفار متماسك للتقديم المبرَّد). فيتا مفتتة. خبز حبوب كاملة منفصل.', 'فطور', 24),
  ('B02', 'فطور', 'فطور', 'باور بول بروتين', 'Power Protein Bowl', 'عالمي', 'عالمي', 48, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'بيض مخفوق مع بياض، بطاطا حلوة مكعبات مشوية، سبانخ سوتيه وطماطم وأفوكادو.', 'فطور', 25),
  ('B03', 'فطور', 'فطور', 'فول مدمس بالطماطم والبيض', 'Foul Medames', 'عربي', 'خليجي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'الفول يُهرس جزئياً مع ثوم وكمون وليمون وزيت زيتون. بيضة مسلوقة وطماطم وخبز حبوب منفصل.', 'فطور', 26),
  ('B04', 'فطور', 'فطور', 'بلاليط خفيف', 'Balaleet Lite', 'إماراتي/خليجي', 'خليجي', 48, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'شعيرية محمّصة تُطهى بالزعفران والهيل مع قليل من العسل (أقل بكثير من الوصفة التقليدية) وتُغطى بأومليت رقيق.', 'فطور', 27),
  ('B05', 'فطور', 'فطور', 'شوفان بالتمر والحليب (ليلي)', 'Date Overnight Oats', 'خليجي', 'خليجي', 72, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', 'يُحضَّر ليلاً ويُحفظ ≤5°م.', 'شوفان + حليب + زبادي يوناني + تمر مفروم + شيا + لوز، يُنقع ليلة كاملة بالثلاجة ≤ 5°م.', 'فطور', 28),
  ('B06', 'فطور', 'فطور', 'أومليت مسالا', 'Masala Omelette', 'هندي', 'عالمي', 48, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'بيض مع بصل وطماطم وفلفل وسبانخ وبهارات المسالا في مقلاة غير لاصقة بقطرة زيت. خبز حبوب منفصل.', 'فطور', 29),
  ('B07', 'فطور', 'فطور', 'تورتيلا إسبانية خفيفة', 'Spanish Tortilla Lite', 'إسباني', 'عالمي', 48, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'بطاطس وبصل تُطهى بالفرن/البخار ثم تُخلط مع البيض والبياض وتُخبز 180°م 25 د (بدل القلي). سلطة طماطم جانبية.', 'فطور', 30),
  ('B08', 'فطور', 'فطور', 'كونجي دجاج بالزنجبيل', 'Chicken Congee', 'صيني/آسيوي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', 'الأرز/الأغذية المطبوخة: التبريد يجب أن يخضع لخطة تبريد مُتحقق منها؛ benchmark دولي: 57→21°م خلال ≤2س ثم إلى ≤5°م خلال إجمالي ≤6س، مع تطبيق المتطلب المحلي/الأكثر تحفظاً عند انطباقه.', 'أرز يُطهى 50–60 د في المرق مع زنجبيل حتى يصير كريمياً، دجاج مسلوق مفتّت، سبانخ وجزر، بيضة مسلوقة وسمسم وقطرة صويا.', 'فطور', 31),
  ('S01', 'سناك', 'سناك', 'كرات التمر والشوفان (3 كرات)', 'Date-Oat Energy Balls', 'خليجي', 'خليجي', 168, 'يُؤكل بارداً أو بحرارة الغرفة', '', 'تمر + شوفان + زبدة فول سوداني + كاكاو تُعجن وتُشكَّل 3 كرات (≈ 20 جم). حفظ مبرَّد.', 'سناك', 32),
  ('S02', 'سناك', 'سناك', 'حمص مقرمش محمّص', 'Crispy Roasted Chickpeas', 'عربي', 'عربي', 96, 'يُؤكل بارداً أو بحرارة الغرفة', 'يُعبَّأ مع كيس مجفّف رطوبة (غذائي).', 'حمص مسلوق مجفَّف جيداً + زيت + بهارات، يُحمَّص 220°م 25–30 د حتى يقرمش. يُعبَّأ مع مجفّف رطوبة؛ يفقد القرمشة مع الرطوبة.', 'سناك', 33),
  ('S03', 'سناك', 'سناك', 'كوب زبادي يوناني وجرانولا', 'Greek Yogurt Granola Cup', 'عالمي', 'عالمي', 72, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'زبادي يوناني + جرانولا منزلية (شوفان ولوز وعسل) + توت. الجرانولا في طبقة منفصلة للحفاظ على القرمشة.', 'سناك', 34),
  ('S04', 'سناك', 'سناك', 'لفائف ديك رومي بالخيار والجبن', 'Turkey Roll-Ups', 'عالمي', 'عالمي', 48, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'شرائح ديك رومي تُلف مع موزاريلا وخيار وخس.', 'سناك', 35),
  ('S05', 'سناك', 'سناك', 'إدامامي بملح البحر والسمسم', 'Edamame', 'ياباني/آسيوي', 'عالمي', 72, 'يُؤكل بارداً أو بحرارة الغرفة', '', 'إدامامي مسلوق 4 د ومبرَّد، رشة ملح بحر وسمسم.', 'سناك', 36),
  ('S06', 'سناك', 'سناك', 'أسياخ دجاج صغيرة', 'Mini Chicken Skewers', 'خليجي/عربي', 'عربي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'مكعبات دجاج صغيرة في زبادي وليمون وبهارات تُشوى حتى 74°م مع فلفل ألوان.', 'سناك', 37),
  ('S07', 'سناك', 'سناك', 'حمص بالطحينة وأعواد خضار', 'Hummus & Veg Sticks', 'عربي', 'عربي', 72, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'حمص مسلوق يُخفق مع طحينة وليمون وثوم وماء بارد حتى كريمي. جزر وخيار وفلفل أعواداً.', 'سناك', 38),
  ('S08', 'سناك', 'سناك', 'قوارب تونة بالخيار', 'Tuna Cucumber Boats', 'عالمي', 'عالمي', 48, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'تونة مصفّاة + زبادي يوناني + ليمون وأعشاب تُحشى في خيار مُفرَّغ.', 'سناك', 39),
  ('SP01', 'شوربة', 'شوربة', 'شوربة عدس بالكمون', 'Lentil Soup', 'عربي', 'عربي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'عدس + جزر + بصل + ثوم + كمون في مرق خفيف 30 د ثم يُهرس جزئياً. عصرة ليمون عند التقديم.', 'شوربة', 40),
  ('SP02', 'شوربة', 'شوربة', 'شوربة شوفان بالدجاج', 'Chicken Oat Soup', 'خليجي', 'خليجي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'دجاج مفتّت + شوفان + جزر وكرفس وبصل في مرق، وقليل من الحليب قليل الدسم بدل الكريمة.', 'شوربة', 41),
  ('SP03', 'شوربة', 'شوربة', 'شوربة يقطين وجزر بالزنجبيل', 'Pumpkin-Carrot Soup', 'عالمي', 'عالمي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'خضار تُسلق ثم تُخفق ناعمة مع زنجبيل وقليل من حليب جوز الهند (بدون كريمة).', 'شوربة', 42),
  ('SP04', 'شوربة', 'شوربة', 'حريرة', 'Harira', 'مغاربي/عربي', 'عربي', 72, 'ميكروويف 2.5–3 د مغطّى مع رشة ماء حتى 74°م في المركز، أو بخار 4 د', '', 'طماطم وكرفس وبصل ومعجون طماطم وأعشاب مع حمص وعدس وقطع دجاج صغيرة، وتُكثَّف بدقيق القمح الكامل المذاب (تمليح).', 'شوربة', 43),
  ('SL01', 'سلطة', 'سلطة', 'كينوا بالدجاج المشوي والأفوكادو', 'Quinoa Chicken Avocado', 'عالمي', 'عالمي', 48, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'كينوا مسلوقة مبرَّدة + دجاج مشوي شرائح + خس وخيار وطماطم كرزية + أفوكادو. الصلصة منفصلة (ليمون وزيت وأعشاب).', 'سلطة', 44),
  ('SL02', 'سلطة', 'سلطة', 'نيسواز تونة', 'Niçoise Salad', 'فرنسي', 'عالمي', 48, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'تونة + بيض مسلوق + بطاطس مسلوقة + فاصوليا خضراء + طماطم كرزية + زيتون + خس. صلصة خل البلسمك والزعتر منفصلة.', 'سلطة', 45),
  ('SL03', 'سلطة', 'سلطة', 'سلطة يونانية بالدجاج', 'Greek Chicken Salad', 'يوناني', 'عالمي', 48, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'خيار وطماطم وفلفل وبصل أحمر وزيتون وفيتا وحمص مع دجاج مشوي. صلصة ليمون وزيت زيتون منفصلة.', 'سلطة', 46),
  ('SL04', 'سلطة', 'سلطة', 'سلمون ببذور اليقطين', 'Salmon & Pumpkin Seeds', 'عالمي', 'عالمي', 48, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'سلمون مشوي بارد على جرجير وخس مع بطاطا حلوة مشوية وبذور يقطين. صلصة خردل خفيفة (ليمون + زبادي يوناني) منفصلة.', 'سلطة', 47),
  ('SL05', 'سلطة', 'سلطة', 'سيزر ربيان خفيف', 'Light Shrimp Caesar', 'أمريكي', 'عالمي', 48, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', 'الكروتون في كيس منفصل للحفاظ على القرمشة.', 'ربيان مشوي 90 ث + خس روماني + كروتون حبوب كاملة مخبوز + بارميزان. صلصة سيزر بالزبادي اليوناني والثوم والليمون منفصلة.', 'سلطة', 48),
  ('D01', 'حلا', 'حلا', 'كيك التمر اللزج الخفيف', 'Light Sticky Date Cake', 'خليجي', 'خليجي', 72, 'يُؤكل بارداً أو بحرارة الغرفة', '', 'تمر مهروس + دقيق قمح كامل + بيض + زبادي يوناني + حليب + قليل زيت، يُخبز 175°م 22–25 د. بدون سكر مضاف. حصة ≈ 100 جم.', 'حلا', 49),
  ('D02', 'حلا', 'حلا', 'كيك الدخن بالتمر واللوز', 'Millet Date Cake', 'خليجي', 'خليجي', 72, 'يُؤكل بارداً أو بحرارة الغرفة', '', 'دقيق دخن + تمر + بيض + زبادي يوناني + لوز مفروم، يُخبز 175°م 25 د. الدخن خالٍ من الغلوتين طبيعياً (تأكد من خلوّ التصنيع من التلوث).', 'حلا', 50),
  ('D03', 'حلا', 'حلا', 'براونيز بروتين بالفاصوليا السوداء', 'Protein Black-Bean Brownie', 'عالمي', 'عالمي', 72, 'يُؤكل بارداً أو بحرارة الغرفة', '', 'فاصوليا سوداء مطبوخة تُخفق ناعمة مع كاكاو وتمر وبيض وشوفان وزبادي يوناني، تُخبز 175°م 20 د. لا يُشعر بطعم الفاصوليا عند الخفق الجيد.', 'حلا', 51),
  ('D04', 'حلا', 'حلا', 'تشيز كيك الزبادي اليوناني بالتوت', 'Greek Yogurt Cheesecake Jar', 'عالمي', 'عالمي', 72, 'يُقدَّم بارداً - الصلصة في كوب منفصل ولا تُخلط قبل الأكل', '', 'زبادي يوناني + بيض + عسل يُخبز في كوب 150°م حتى يتماسك ثم يُبرَّد 6 س. قاعدة شوفان وتمر وطبقة توت.', 'حلا', 52)
on conflict (id) do update set
  section = excluded.section, category = excluded.category, name = excluded.name,
  name_en = excluded.name_en, cuisine = excluded.cuisine, identity = excluded.identity,
  shelf_life_h = excluded.shelf_life_h, reheat = excluded.reheat,
  ops_note = excluded.ops_note, method = excluded.method,
  eng_group = excluded.eng_group, sort_order = excluded.sort_order;

-- 457 سطر وصفة (تُستبدل بالكامل)
delete from ops_recipe_lines;
insert into ops_recipe_lines (sku, type, ing, grams, sort_order) values
  ('C01', 'P', 'chicken_breast', 160, 0),
  ('C01', 'C', 'basmati', 60, 1),
  ('C01', 'V', 'tomato', 40, 2),
  ('C01', 'V', 'onion', 30, 3),
  ('C01', 'V', 'carrot', 25, 4),
  ('C01', 'V', 'garlic', 5, 5),
  ('C01', 'S', 'olive_oil', 5, 6),
  ('C01', 'S', 'tomato_paste', 10, 7),
  ('C01', 'S', 'spice', 6, 8),
  ('C01', 'S', 'chicken_stock', 120, 9),
  ('C01', 'S', 'almonds', 5, 10),
  ('C02', 'P', 'chicken_breast', 160, 11),
  ('C02', 'C', 'basmati', 60, 12),
  ('C02', 'V', 'onion', 45, 13),
  ('C02', 'V', 'tomato', 40, 14),
  ('C02', 'V', 'garlic', 5, 15),
  ('C02', 'S', 'olive_oil', 5, 16),
  ('C02', 'S', 'tomato_paste', 8, 17),
  ('C02', 'S', 'spice', 6, 18),
  ('C02', 'S', 'chicken_stock', 120, 19),
  ('C02', 'S', 'lemon_juice', 5, 20),
  ('C03', 'P', 'chicken_breast', 110, 21),
  ('C03', 'P', 'chicken_thigh', 50, 22),
  ('C03', 'C', 'basmati', 55, 23),
  ('C03', 'V', 'cucumber', 50, 24),
  ('C03', 'V', 'tomato', 50, 25),
  ('C03', 'V', 'romaine', 30, 26),
  ('C03', 'S', 'yogurt_low', 40, 27),
  ('C03', 'S', 'garlic', 4, 28),
  ('C03', 'S', 'lemon_juice', 10, 29),
  ('C03', 'S', 'olive_oil', 5, 30),
  ('C03', 'S', 'spice', 5, 31),
  ('C04', 'P', 'chicken_breast', 160, 32),
  ('C04', 'S', 'yogurt_low', 40, 33),
  ('C04', 'S', 'lemon_juice', 12, 34),
  ('C04', 'S', 'garlic', 5, 35),
  ('C04', 'S', 'olive_oil', 5, 36),
  ('C04', 'S', 'spice', 4, 37),
  ('C04', 'S', 'tomato_paste', 8, 38),
  ('C04', 'C', 'basmati', 50, 39),
  ('C04', 'C', 'vermicelli', 10, 40),
  ('C04', 'V', 'bell_pepper', 60, 41),
  ('C04', 'V', 'onion', 40, 42),
  ('C04', 'V', 'tomato', 40, 43),
  ('C05', 'P', 'chicken_breast', 160, 44),
  ('C05', 'C', 'basmati', 50, 45),
  ('C05', 'S', 'greek_yogurt', 50, 46),
  ('C05', 'S', 'tomato_crushed', 90, 47),
  ('C05', 'V', 'onion', 50, 48),
  ('C05', 'S', 'garlic', 5, 49),
  ('C05', 'S', 'ginger', 5, 50),
  ('C05', 'S', 'coconut_milk', 20, 51),
  ('C05', 'S', 'olive_oil', 3, 52),
  ('C05', 'S', 'spice', 6, 53),
  ('C05', 'V', 'cauliflower', 60, 54),
  ('C06', 'P', 'chicken_breast', 160, 55),
  ('C06', 'C', 'basmati', 60, 56),
  ('C06', 'S', 'greek_yogurt', 40, 57),
  ('C06', 'V', 'onion', 50, 58),
  ('C06', 'V', 'tomato', 30, 59),
  ('C06', 'S', 'garlic', 4, 60),
  ('C06', 'S', 'ginger', 4, 61),
  ('C06', 'S', 'olive_oil', 6, 62),
  ('C06', 'S', 'spice', 7, 63),
  ('C06', 'V', 'carrot', 30, 64),
  ('C06', 'S', 'chicken_stock', 80, 65),
  ('C06', 'S', 'herbs', 8, 66),
  ('C07', 'P', 'chicken_breast', 160, 67),
  ('C07', 'C', 'brown_rice', 55, 68),
  ('C07', 'V', 'broccoli', 90, 69),
  ('C07', 'V', 'carrot', 30, 70),
  ('C07', 'S', 'soy_sauce', 12, 71),
  ('C07', 'S', 'honey', 8, 72),
  ('C07', 'S', 'garlic', 4, 73),
  ('C07', 'S', 'ginger', 4, 74),
  ('C07', 'S', 'sesame', 3, 75),
  ('C07', 'S', 'olive_oil', 4, 76),
  ('C08', 'P', 'chicken_breast', 160, 77),
  ('C08', 'C', 'brown_rice', 45, 78),
  ('C08', 'C', 'black_beans', 40, 79),
  ('C08', 'V', 'bell_pepper', 80, 80),
  ('C08', 'V', 'onion', 50, 81),
  ('C08', 'V', 'tomato', 40, 82),
  ('C08', 'S', 'avocado', 15, 83),
  ('C08', 'S', 'lemon_juice', 10, 84),
  ('C08', 'S', 'spice', 5, 85),
  ('C08', 'S', 'olive_oil', 6, 86),
  ('C08', 'S', 'greek_yogurt', 20, 87),
  ('C09', 'P', 'chicken_breast', 160, 88),
  ('C09', 'C', 'potato', 180, 89),
  ('C09', 'V', 'zucchini', 80, 90),
  ('C09', 'V', 'green_beans', 60, 91),
  ('C09', 'S', 'olive_oil', 8, 92),
  ('C09', 'S', 'lemon_juice', 15, 93),
  ('C09', 'S', 'garlic', 4, 94),
  ('C09', 'S', 'herbs', 6, 95),
  ('C09', 'S', 'spice', 2, 96),
  ('C10', 'P', 'chicken_breast', 110, 97),
  ('C10', 'P', 'chicken_thigh', 50, 98),
  ('C10', 'C', 'ww_pasta', 55, 99),
  ('C10', 'V', 'bell_pepper', 50, 100),
  ('C10', 'V', 'mushroom', 50, 101),
  ('C10', 'V', 'onion', 40, 102),
  ('C10', 'S', 'tomato_crushed', 120, 103),
  ('C10', 'S', 'olives', 10, 104),
  ('C10', 'S', 'olive_oil', 6, 105),
  ('C10', 'S', 'garlic', 4, 106),
  ('C10', 'S', 'herbs', 3, 107),
  ('C11', 'P', 'chicken_breast', 160, 108),
  ('C11', 'C', 'sweet_potato', 160, 109),
  ('C11', 'V', 'corn', 50, 110),
  ('C11', 'V', 'bell_pepper', 50, 111),
  ('C11', 'S', 'tomato_paste', 20, 112),
  ('C11', 'S', 'honey', 6, 113),
  ('C11', 'S', 'balsamic', 8, 114),
  ('C11', 'S', 'spice', 4, 115),
  ('C11', 'S', 'olive_oil', 5, 116),
  ('C11', 'S', 'garlic', 3, 117),
  ('C12', 'P', 'chicken_breast', 160, 118),
  ('C12', 'C', 'jareesh', 55, 119),
  ('C12', 'V', 'onion', 50, 120),
  ('C12', 'V', 'carrot', 30, 121),
  ('C12', 'V', 'tomato', 30, 122),
  ('C12', 'S', 'yogurt_low', 50, 123),
  ('C12', 'S', 'olive_oil', 5, 124),
  ('C12', 'S', 'spice', 4, 125),
  ('C12', 'S', 'chicken_stock', 150, 126),
  ('C12', 'V', 'garlic', 4, 127),
  ('C12', 'S', 'ghee', 3, 128),
  ('M01', 'P', 'lamb_leg', 160, 129),
  ('M01', 'C', 'basmati', 60, 130),
  ('M01', 'V', 'onion', 40, 131),
  ('M01', 'V', 'tomato', 40, 132),
  ('M01', 'S', 'ghee', 3, 133),
  ('M01', 'S', 'spice', 6, 134),
  ('M01', 'S', 'chicken_stock', 100, 135),
  ('M01', 'V', 'cucumber', 30, 136),
  ('M02', 'P', 'beef_sirloin', 150, 137),
  ('M02', 'C', 'basmati', 55, 138),
  ('M02', 'V', 'tomato', 80, 139),
  ('M02', 'V', 'onion', 50, 140),
  ('M02', 'V', 'bell_pepper', 50, 141),
  ('M02', 'S', 'garlic', 5, 142),
  ('M02', 'S', 'olive_oil', 6, 143),
  ('M02', 'S', 'spice', 4, 144),
  ('M02', 'S', 'tomato_paste', 8, 145),
  ('M03', 'P', 'beef_mince', 130, 146),
  ('M03', 'C', 'ww_pasta', 40, 147),
  ('M03', 'V', 'zucchini', 80, 148),
  ('M03', 'V', 'onion', 30, 149),
  ('M03', 'V', 'spinach', 40, 150),
  ('M03', 'S', 'tomato_crushed', 120, 151),
  ('M03', 'S', 'mozzarella', 25, 152),
  ('M03', 'S', 'milk_low', 60, 153),
  ('M03', 'S', 'ww_flour', 6, 154),
  ('M03', 'S', 'olive_oil', 4, 155),
  ('M03', 'S', 'garlic', 3, 156),
  ('M03', 'S', 'herbs', 2, 157),
  ('M03', 'S', 'parmesan', 3, 158),
  ('M04', 'P', 'beef_sirloin', 150, 159),
  ('M04', 'C', 'brown_rice', 55, 160),
  ('M04', 'V', 'broccoli', 140, 161),
  ('M04', 'V', 'carrot', 30, 162),
  ('M04', 'S', 'soy_sauce', 12, 163),
  ('M04', 'S', 'honey', 5, 164),
  ('M04', 'S', 'garlic', 4, 165),
  ('M04', 'S', 'ginger', 5, 166),
  ('M04', 'S', 'olive_oil', 5, 167),
  ('M04', 'S', 'sesame', 3, 168),
  ('M05', 'P', 'beef_mince', 150, 169),
  ('M05', 'C', 'potato', 140, 170),
  ('M05', 'V', 'romaine', 50, 171),
  ('M05', 'V', 'tomato', 50, 172),
  ('M05', 'V', 'onion', 20, 173),
  ('M05', 'V', 'cucumber', 30, 174),
  ('M05', 'S', 'mozzarella', 15, 175),
  ('M05', 'S', 'greek_yogurt', 25, 176),
  ('M05', 'S', 'tomato_paste', 8, 177),
  ('M05', 'S', 'olive_oil', 4, 178),
  ('M05', 'S', 'spice', 3, 179),
  ('M06', 'P', 'beef_mince', 150, 180),
  ('M06', 'V', 'onion', 20, 181),
  ('M06', 'S', 'herbs', 10, 182),
  ('M06', 'S', 'spice', 4, 183),
  ('M06', 'C', 'bulgur', 50, 184),
  ('M06', 'V', 'tomato', 60, 185),
  ('M06', 'V', 'cucumber', 50, 186),
  ('M06', 'S', 'tahini', 12, 187),
  ('M06', 'S', 'lemon_juice', 10, 188),
  ('M06', 'S', 'olive_oil', 3, 189),
  ('F01', 'P', 'hammour', 170, 190),
  ('F01', 'C', 'basmati', 55, 191),
  ('F01', 'V', 'onion', 70, 192),
  ('F01', 'V', 'tomato', 30, 193),
  ('F01', 'S', 'olive_oil', 7, 194),
  ('F01', 'S', 'spice', 5, 195),
  ('F01', 'S', 'garlic', 4, 196),
  ('F01', 'S', 'lemon_juice', 8, 197),
  ('F02', 'P', 'shrimp', 180, 198),
  ('F02', 'C', 'basmati', 55, 199),
  ('F02', 'V', 'onion', 40, 200),
  ('F02', 'V', 'tomato', 40, 201),
  ('F02', 'V', 'garlic', 4, 202),
  ('F02', 'S', 'olive_oil', 6, 203),
  ('F02', 'S', 'tomato_paste', 8, 204),
  ('F02', 'S', 'spice', 6, 205),
  ('F02', 'S', 'lemon_juice', 6, 206),
  ('F03', 'P', 'salmon', 130, 207),
  ('F03', 'C', 'quinoa', 45, 208),
  ('F03', 'V', 'broccoli', 100, 209),
  ('F03', 'V', 'green_beans', 70, 210),
  ('F03', 'S', 'greek_yogurt', 35, 211),
  ('F03', 'S', 'lemon_juice', 12, 212),
  ('F03', 'S', 'herbs', 6, 213),
  ('F03', 'S', 'olive_oil', 3, 214),
  ('F03', 'S', 'garlic', 3, 215),
  ('F04', 'P', 'white_fish', 170, 216),
  ('F04', 'C', 'basmati', 55, 217),
  ('F04', 'S', 'coconut_milk', 45, 218),
  ('F04', 'S', 'tomato_crushed', 80, 219),
  ('F04', 'V', 'onion', 50, 220),
  ('F04', 'V', 'spinach', 50, 221),
  ('F04', 'S', 'garlic', 4, 222),
  ('F04', 'S', 'ginger', 5, 223),
  ('F04', 'S', 'olive_oil', 4, 224),
  ('F04', 'S', 'spice', 6, 225),
  ('F05', 'P', 'white_fish', 170, 226),
  ('F05', 'C', 'potato', 120, 227),
  ('F05', 'V', 'tomato', 100, 228),
  ('F05', 'V', 'bell_pepper', 50, 229),
  ('F05', 'V', 'zucchini', 60, 230),
  ('F05', 'V', 'onion', 40, 231),
  ('F05', 'S', 'olive_oil', 6, 232),
  ('F05', 'S', 'spice', 5, 233),
  ('F05', 'S', 'garlic', 4, 234),
  ('F05', 'S', 'lemon_juice', 8, 235),
  ('F05', 'S', 'olives', 10, 236),
  ('F05', 'S', 'herbs', 6, 237),
  ('F06', 'P', 'shrimp', 160, 238),
  ('F06', 'P', 'egg_whole', 50, 239),
  ('F06', 'C', 'brown_rice', 55, 240),
  ('F06', 'V', 'carrot', 30, 241),
  ('F06', 'V', 'peas', 30, 242),
  ('F06', 'V', 'onion', 30, 243),
  ('F06', 'V', 'cabbage', 40, 244),
  ('F06', 'S', 'soy_sauce', 10, 245),
  ('F06', 'S', 'olive_oil', 6, 246),
  ('F06', 'S', 'garlic', 4, 247),
  ('F06', 'S', 'ginger', 3, 248),
  ('F06', 'S', 'sesame', 2, 249),
  ('B01', 'P', 'egg_whole', 100, 250),
  ('B01', 'S', 'tomato_crushed', 130, 251),
  ('B01', 'V', 'bell_pepper', 50, 252),
  ('B01', 'V', 'onion', 40, 253),
  ('B01', 'V', 'spinach', 30, 254),
  ('B01', 'S', 'olive_oil', 5, 255),
  ('B01', 'S', 'garlic', 3, 256),
  ('B01', 'S', 'spice', 3, 257),
  ('B01', 'C', 'ww_bread', 50, 258),
  ('B01', 'S', 'feta', 15, 259),
  ('B02', 'P', 'egg_whole', 100, 260),
  ('B02', 'P', 'egg_white', 60, 261),
  ('B02', 'C', 'sweet_potato', 100, 262),
  ('B02', 'V', 'spinach', 40, 263),
  ('B02', 'V', 'tomato', 50, 264),
  ('B02', 'S', 'avocado', 40, 265),
  ('B02', 'S', 'olive_oil', 3, 266),
  ('B02', 'S', 'spice', 2, 267),
  ('B03', 'P', 'fava_cooked', 200, 268),
  ('B03', 'P', 'egg_whole', 50, 269),
  ('B03', 'V', 'tomato', 50, 270),
  ('B03', 'V', 'onion', 20, 271),
  ('B03', 'S', 'lemon_juice', 12, 272),
  ('B03', 'S', 'olive_oil', 6, 273),
  ('B03', 'S', 'spice', 2, 274),
  ('B03', 'C', 'ww_bread', 30, 275),
  ('B04', 'C', 'vermicelli', 45, 276),
  ('B04', 'S', 'honey', 8, 277),
  ('B04', 'S', 'spice', 2, 278),
  ('B04', 'P', 'egg_whole', 100, 279),
  ('B04', 'P', 'egg_white', 30, 280),
  ('B04', 'S', 'olive_oil', 3, 281),
  ('B05', 'C', 'oats', 40, 282),
  ('B05', 'S', 'milk_low', 120, 283),
  ('B05', 'P', 'greek_yogurt', 80, 284),
  ('B05', 'S', 'dates', 25, 285),
  ('B05', 'S', 'chia', 8, 286),
  ('B05', 'S', 'almonds', 8, 287),
  ('B06', 'P', 'egg_whole', 150, 288),
  ('B06', 'P', 'egg_white', 30, 289),
  ('B06', 'V', 'onion', 30, 290),
  ('B06', 'V', 'tomato', 40, 291),
  ('B06', 'V', 'bell_pepper', 30, 292),
  ('B06', 'V', 'spinach', 20, 293),
  ('B06', 'S', 'olive_oil', 5, 294),
  ('B06', 'S', 'spice', 2, 295),
  ('B06', 'C', 'ww_bread', 40, 296),
  ('B07', 'P', 'egg_whole', 150, 297),
  ('B07', 'P', 'egg_white', 30, 298),
  ('B07', 'C', 'potato', 120, 299),
  ('B07', 'V', 'onion', 40, 300),
  ('B07', 'S', 'olive_oil', 8, 301),
  ('B07', 'V', 'tomato', 60, 302),
  ('B08', 'P', 'chicken_breast', 100, 303),
  ('B08', 'C', 'basmati', 45, 304),
  ('B08', 'S', 'ginger', 6, 305),
  ('B08', 'V', 'carrot', 30, 306),
  ('B08', 'S', 'soy_sauce', 6, 307),
  ('B08', 'S', 'sesame', 2, 308),
  ('B08', 'P', 'egg_whole', 50, 309),
  ('B08', 'V', 'spinach', 30, 310),
  ('B08', 'S', 'chicken_stock', 300, 311),
  ('S01', 'C', 'oats', 20, 312),
  ('S01', 'S', 'dates', 25, 313),
  ('S01', 'S', 'peanut_butter', 10, 314),
  ('S01', 'S', 'cocoa', 3, 315),
  ('S02', 'C', 'chickpea_cooked', 100, 316),
  ('S02', 'S', 'olive_oil', 3, 317),
  ('S02', 'S', 'spice', 2, 318),
  ('S03', 'P', 'greek_yogurt', 170, 319),
  ('S03', 'C', 'oats', 20, 320),
  ('S03', 'S', 'almonds', 8, 321),
  ('S03', 'S', 'honey', 6, 322),
  ('S03', 'S', 'berries', 40, 323),
  ('S04', 'P', 'turkey_slices', 70, 324),
  ('S04', 'S', 'mozzarella', 20, 325),
  ('S04', 'V', 'cucumber', 50, 326),
  ('S04', 'V', 'romaine', 30, 327),
  ('S05', 'P', 'edamame', 120, 328),
  ('S05', 'S', 'sesame', 2, 329),
  ('S05', 'S', 'spice', 1, 330),
  ('S06', 'P', 'chicken_breast', 100, 331),
  ('S06', 'S', 'yogurt_low', 20, 332),
  ('S06', 'S', 'lemon_juice', 5, 333),
  ('S06', 'S', 'spice', 2, 334),
  ('S06', 'S', 'olive_oil', 2, 335),
  ('S06', 'V', 'bell_pepper', 40, 336),
  ('S07', 'C', 'chickpea_cooked', 70, 337),
  ('S07', 'S', 'tahini', 8, 338),
  ('S07', 'S', 'lemon_juice', 10, 339),
  ('S07', 'S', 'garlic', 2, 340),
  ('S07', 'V', 'carrot', 50, 341),
  ('S07', 'V', 'cucumber', 60, 342),
  ('S07', 'V', 'bell_pepper', 40, 343),
  ('S08', 'P', 'tuna', 80, 344),
  ('S08', 'S', 'greek_yogurt', 25, 345),
  ('S08', 'V', 'cucumber', 120, 346),
  ('S08', 'S', 'lemon_juice', 5, 347),
  ('S08', 'V', 'onion', 10, 348),
  ('S08', 'S', 'herbs', 3, 349),
  ('S08', 'S', 'spice', 1, 350),
  ('SP01', 'C', 'lentil_dry', 40, 351),
  ('SP01', 'V', 'carrot', 40, 352),
  ('SP01', 'V', 'onion', 40, 353),
  ('SP01', 'S', 'garlic', 3, 354),
  ('SP01', 'S', 'olive_oil', 4, 355),
  ('SP01', 'S', 'spice', 2, 356),
  ('SP01', 'S', 'lemon_juice', 8, 357),
  ('SP01', 'S', 'chicken_stock', 250, 358),
  ('SP02', 'P', 'chicken_breast', 60, 359),
  ('SP02', 'C', 'oats', 25, 360),
  ('SP02', 'V', 'carrot', 30, 361),
  ('SP02', 'V', 'celery', 20, 362),
  ('SP02', 'V', 'onion', 30, 363),
  ('SP02', 'S', 'olive_oil', 3, 364),
  ('SP02', 'S', 'chicken_stock', 250, 365),
  ('SP02', 'S', 'milk_low', 50, 366),
  ('SP02', 'S', 'spice', 1, 367),
  ('SP03', 'V', 'pumpkin', 150, 368),
  ('SP03', 'V', 'carrot', 60, 369),
  ('SP03', 'V', 'onion', 30, 370),
  ('SP03', 'S', 'ginger', 4, 371),
  ('SP03', 'S', 'olive_oil', 4, 372),
  ('SP03', 'S', 'coconut_milk', 15, 373),
  ('SP03', 'S', 'chicken_stock', 200, 374),
  ('SP04', 'C', 'chickpea_cooked', 40, 375),
  ('SP04', 'C', 'lentil_dry', 20, 376),
  ('SP04', 'V', 'tomato', 100, 377),
  ('SP04', 'V', 'onion', 30, 378),
  ('SP04', 'V', 'celery', 20, 379),
  ('SP04', 'S', 'tomato_paste', 10, 380),
  ('SP04', 'S', 'herbs', 10, 381),
  ('SP04', 'S', 'spice', 3, 382),
  ('SP04', 'P', 'chicken_breast', 50, 383),
  ('SP04', 'S', 'olive_oil', 4, 384),
  ('SP04', 'S', 'chicken_stock', 200, 385),
  ('SP04', 'S', 'ww_flour', 6, 386),
  ('SL01', 'P', 'chicken_breast', 120, 387),
  ('SL01', 'C', 'quinoa', 35, 388),
  ('SL01', 'V', 'romaine', 60, 389),
  ('SL01', 'V', 'cucumber', 50, 390),
  ('SL01', 'V', 'tomato', 60, 391),
  ('SL01', 'S', 'avocado', 40, 392),
  ('SL01', 'S', 'olive_oil', 6, 393),
  ('SL01', 'S', 'lemon_juice', 12, 394),
  ('SL01', 'S', 'herbs', 3, 395),
  ('SL02', 'P', 'tuna', 90, 396),
  ('SL02', 'P', 'egg_whole', 50, 397),
  ('SL02', 'C', 'potato', 100, 398),
  ('SL02', 'V', 'green_beans', 70, 399),
  ('SL02', 'V', 'tomato', 60, 400),
  ('SL02', 'S', 'olives', 15, 401),
  ('SL02', 'V', 'onion', 15, 402),
  ('SL02', 'V', 'romaine', 40, 403),
  ('SL02', 'S', 'olive_oil', 6, 404),
  ('SL02', 'S', 'balsamic', 8, 405),
  ('SL02', 'S', 'herbs', 2, 406),
  ('SL03', 'P', 'chicken_breast', 80, 407),
  ('SL03', 'C', 'chickpea_cooked', 60, 408),
  ('SL03', 'S', 'feta', 40, 409),
  ('SL03', 'V', 'cucumber', 80, 410),
  ('SL03', 'V', 'tomato', 80, 411),
  ('SL03', 'V', 'bell_pepper', 40, 412),
  ('SL03', 'V', 'onion', 25, 413),
  ('SL03', 'S', 'olives', 20, 414),
  ('SL03', 'S', 'olive_oil', 7, 415),
  ('SL03', 'S', 'lemon_juice', 10, 416),
  ('SL04', 'P', 'salmon', 110, 417),
  ('SL04', 'V', 'arugula', 50, 418),
  ('SL04', 'V', 'romaine', 40, 419),
  ('SL04', 'C', 'sweet_potato', 80, 420),
  ('SL04', 'S', 'pumpkin_seeds', 8, 421),
  ('SL04', 'S', 'lemon_juice', 12, 422),
  ('SL04', 'S', 'olive_oil', 4, 423),
  ('SL04', 'S', 'greek_yogurt', 20, 424),
  ('SL05', 'P', 'shrimp', 130, 425),
  ('SL05', 'V', 'romaine', 100, 426),
  ('SL05', 'C', 'ww_bread', 25, 427),
  ('SL05', 'S', 'parmesan', 10, 428),
  ('SL05', 'S', 'greek_yogurt', 40, 429),
  ('SL05', 'S', 'lemon_juice', 10, 430),
  ('SL05', 'S', 'garlic', 3, 431),
  ('SL05', 'S', 'olive_oil', 4, 432),
  ('D01', 'S', 'dates', 30, 433),
  ('D01', 'C', 'ww_flour', 20, 434),
  ('D01', 'S', 'egg_whole', 25, 435),
  ('D01', 'S', 'greek_yogurt', 30, 436),
  ('D01', 'S', 'milk_low', 20, 437),
  ('D01', 'S', 'olive_oil', 4, 438),
  ('D02', 'C', 'millet_flour', 25, 439),
  ('D02', 'S', 'dates', 20, 440),
  ('D02', 'S', 'egg_whole', 25, 441),
  ('D02', 'S', 'greek_yogurt', 30, 442),
  ('D02', 'S', 'almonds', 6, 443),
  ('D02', 'S', 'olive_oil', 3, 444),
  ('D03', 'S', 'black_beans', 50, 445),
  ('D03', 'S', 'cocoa', 8, 446),
  ('D03', 'S', 'dates', 20, 447),
  ('D03', 'S', 'egg_whole', 40, 448),
  ('D03', 'C', 'oats', 10, 449),
  ('D03', 'S', 'greek_yogurt', 25, 450),
  ('D04', 'S', 'greek_yogurt', 130, 451),
  ('D04', 'S', 'egg_whole', 30, 452),
  ('D04', 'S', 'honey', 8, 453),
  ('D04', 'C', 'oats', 15, 454),
  ('D04', 'S', 'dates', 10, 455),
  ('D04', 'S', 'berries', 40, 456)
;

-- 8 بوابة اعتماد (قيم بداية — لا تُكتب فوق الموجود)
insert into ops_gate_defs (gate_index, label, kind, owner_role, resets_on_recipe_change, active, note) values
  (0, 'مطبخ + Pilot', 'kitchen_pilot', null, true, true, 'تُحسب آلياً: تجارب ناجحة بالعدد المطلوب + قرار الشيف'),
  (1, 'مكوّنات وموردون', 'standard', 'quality'::staff_role, false, true, 'كل مكوّن له مورد معتمد وسعر موثّق'),
  (2, 'حساسية', 'standard', 'quality'::staff_role, true, true, 'إقرار مسببات الحساسية والمواد الخفية'),
  (3, 'تغذية', 'standard', 'quality'::staff_role, true, true, 'القيم الغذائية واتساقها مع الماكروز'),
  (4, 'سلامة الغذاء', 'standard', 'quality'::staff_role, false, true, 'HACCP والحدود الحرجة'),
  (5, 'صلاحية', 'shelf', 'quality'::staff_role, false, true, 'الصلاحية المعلنة مدعومة باختبار'),
  (6, 'ملصق', 'standard', 'quality'::staff_role, true, true, 'الملصق يطابق الوصفة والقيم'),
  (7, 'سعر وهامش', 'price', 'executive'::staff_role, true, true, 'السعر يغطي التكلفة الكاملة بهامش مقبول')
on conflict (gate_index) do nothing;

-- 3 اعتماد مكوّن (قيم بداية)
insert into ops_ing_approval_defs (approval_index, label, kind, owner_role, active, note) values
  (0, 'اعتماد المورد', 'supplier', 'quality'::staff_role, true, 'مورد معروف وشهاداته سارية'),
  (1, 'إقرار الحساسية', 'allergen', 'quality'::staff_role, true, 'مسببات الحساسية والمواد الخفية موثّقة'),
  (2, 'سعر موثّق', 'price', 'executive'::staff_role, true, 'عرض سعر محدّث من المورد')
on conflict (approval_index) do nothing;

-- 5 محور جاهزية (قيم بداية — لا تُكتب فوق الموجود)
insert into ops_launch_axes (axis_index, label, kind, active, note) values
  (1, 'بوابة المطبخ', 'kitchen_gate', true, 'تجارب الطبخ وقرار الشيف — المحور الوحيد المذكور بالاسم في ورقة لوحة التحكم'),
  (2, 'بوابات الاعتماد', 'sku_gates', true, 'الصنف ما يُنشر إلا بعد ختم كل بوابة نشطة من صاحبها'),
  (3, 'المكوّنات والموردون', 'ingredients', true, 'المواصفة والمورد والحساسية والسعر لكل مكوّن مستخدم في وصفة'),
  (4, 'سلامة الغذاء', 'food_safety', true, 'خطة HACCP وحدودها وسجل المراقبة والبرامج التمهيدية وعدم المطابقة'),
  (5, 'الإنتاج والهوامش', 'production', true, 'جدول الدوران وخطة الحصص وحد الهامش')
on conflict (axis_index) do nothing;

-- 25 نوع طلب تغيير (قائمة بيضاء — لا تُكتب فوق الموجود)
insert into ops_change_kinds (kind, label, area, target_table, strategy, key_columns, patch_columns, requester_roles, approver_role, active, note) values
  ('gate.set', 'ختم بوابة اعتماد', 'بوابات الاعتماد', 'ops_gates', 'upsert'::change_strategy, array['sku', 'gate_index']::text[], array['status', 'note', 'approved_by_name', 'approved_at']::text[], array['quality'::staff_role, 'executive'::staff_role], 'executive'::staff_role, true, 'ختم بوابة على صنف — يُطبَّق بعد الاعتماد فقط'),
  ('ing_approval.set', 'اعتماد مكوّن', 'المكوّنات', 'ops_ing_approvals', 'upsert'::change_strategy, array['ing_key', 'approval_index']::text[], array['status', 'note', 'approved_by_name', 'approved_at']::text[], array['quality'::staff_role, 'executive'::staff_role], 'executive'::staff_role, true, 'اعتماد مواصفة أو مورد أو حساسية أو سعر مكوّن'),
  ('ingredient.specs', 'مواصفة مكوّن', 'المكوّنات', 'ops_ingredients', 'upsert'::change_strategy, array['key']::text[], array['kcal', 'protein', 'carb', 'fat', 'fiber', 'allergen_text', 'flags', 'source', 'hidden', 'supplier', 'supplier_note']::text[], array['quality'::staff_role], 'executive'::staff_role, true, 'القيم الغذائية والحساسية والمورد — السعر نوع منفصل'),
  ('ingredient.price', 'سعر مكوّن', 'المكوّنات', 'ops_ingredients', 'upsert'::change_strategy, array['key']::text[], array['price', 'price_quote_date']::text[], array['executive'::staff_role], 'executive'::staff_role, true, 'السعر يمسّ كل الأطباق اللي تستخدم المكوّن'),
  ('shelf_life.set', 'صلاحية صنف', 'الجودة', 'ops_shelf_life', 'upsert'::change_strategy, array['sku']::text[], array['hours']::text[], array['quality'::staff_role], 'executive'::staff_role, true, 'الصلاحية المعلنة بالساعات'),
  ('production.set', 'حصص الإنتاج', 'الإنتاج', 'ops_production', 'upsert'::change_strategy, array['day_index', 'slot']::text[], array['portions']::text[], array['kitchen'::staff_role], 'executive'::staff_role, true, 'عدد الحصص المخططة لخانة في يوم'),
  ('units_sold.set', 'مبيعات صنف', 'هندسة المنيو', 'ops_units_sold', 'upsert'::change_strategy, array['sku']::text[], array['units']::text[], array['executive'::staff_role], 'executive'::staff_role, true, 'الوحدات المباعة — أساس تصنيف هندسة المنيو'),
  ('pilot.set', 'تجربة Pilot', 'بوابة المطبخ', 'ops_pilot_trials', 'upsert'::change_strategy, array['sku', 'trial_index']::text[], array['result', 'cooked_portion_g', 'trial_date', 'notes']::text[], array['quality'::staff_role], 'executive'::staff_role, true, 'نتيجة تجربة طبخ — تدخل في حساب بوابة المطبخ'),
  ('kitchen_gate.set', 'قرار الشيف', 'بوابة المطبخ', 'ops_kitchen_gate', 'upsert'::change_strategy, array['sku']::text[], array['chef_decision', 'chef_name', 'approved_at', 'note']::text[], array['kitchen'::staff_role], 'executive'::staff_role, true, 'قرار الشيف على جاهزية الصنف للإنتاج'),
  ('settings.save', 'إعدادات التكلفة والحدود', 'الإعدادات', 'ops_settings', 'upsert'::change_strategy, array['id']::text[], array['data']::text[], array['executive'::staff_role], 'executive'::staff_role, true, 'مضاعفات الحصص ونسب التكلفة وحدود الجودة وحد الإطلاق'),
  ('recipe.replace', 'وصفة صنف', 'الوصفات', 'ops_recipe_lines', 'replace_lines'::change_strategy, array['sku']::text[], array['type', 'ing', 'grams', 'sort_order']::text[], array['kitchen'::staff_role], 'executive'::staff_role, true, 'أسطر الوصفة كاملة — تعديلها يصفّر البوابات المرتبطة بها'),
  ('rotation.set', 'خانة جدول الدوران', 'جدول الدوران', 'ops_rotation', 'upsert'::change_strategy, array['day_index', 'slot']::text[], array['sku']::text[], array['kitchen'::staff_role], 'executive'::staff_role, true, 'الصنف المخصّص لخانة في يوم من أيام الدوران'),
  ('gate_def.set', 'تعريف بوابة اعتماد', 'بوابات الاعتماد', 'ops_gate_defs', 'upsert'::change_strategy, array['gate_index']::text[], array['label', 'kind', 'owner_role', 'resets_on_recipe_change', 'active', 'note']::text[], array['executive'::staff_role], 'executive'::staff_role, true, 'إضافة بوابة أو إيقافها أو نقل ملكيتها'),
  ('ing_approval_def.set', 'تعريف اعتماد مكوّن', 'المكوّنات', 'ops_ing_approval_defs', 'upsert'::change_strategy, array['approval_index']::text[], array['label', 'kind', 'owner_role', 'active', 'note']::text[], array['executive'::staff_role], 'executive'::staff_role, true, 'إضافة اعتماد مكوّن أو إيقافه أو نقل ملكيته'),
  ('launch_axis.set', 'محور جاهزية الإطلاق', 'قرار الإطلاق', 'ops_launch_axes', 'upsert'::change_strategy, array['axis_index']::text[], array['label', 'kind', 'active', 'note']::text[], array['executive'::staff_role], 'executive'::staff_role, true, 'تعريف محاور قرار الإطلاق'),
  ('ccp.log', 'قراءة نقطة تحكّم حرجة', 'سلامة الغذاء', 'safety_ccp_log', 'insert'::change_strategy, '{}'::text[], array['limit_id', 'log_date', 'shift', 'reading_value', 'reading_bool', 'out_of_limit_note', 'corrective_action', 'recorded_by', 'recorded_by_name']::text[], array['kitchen'::staff_role, 'quality'::staff_role], 'executive'::staff_role, false, 'قراءة مراقبة — الحكم بالنجاح أو الخروج عن الحد يحسبه محفّز في القاعدة — واقعة تُسجَّل فوراً، ما تمر بمسار الاعتماد'),
  ('ccp.verify', 'اعتماد قراءة مراقبة', 'سلامة الغذاء', 'safety_ccp_log', 'upsert'::change_strategy, array['id']::text[], array['verified_by', 'verified_by_name', 'verified_at']::text[], array['quality'::staff_role], 'executive'::staff_role, false, 'التوقيع الثاني على قراءة — واقعة تُسجَّل فوراً، ما تمر بمسار الاعتماد'),
  ('prp.log', 'تسجيل برنامج تمهيدي', 'سلامة الغذاء', 'safety_prp_log', 'upsert'::change_strategy, array['prp_code', 'log_date']::text[], array['done', 'note', 'recorded_by', 'recorded_by_name']::text[], array['kitchen'::staff_role, 'quality'::staff_role], 'executive'::staff_role, false, 'تنفيذ برنامج تمهيدي في يوم — واقعة تُسجَّل فوراً، ما تمر بمسار الاعتماد'),
  ('ncr.raise', 'رفع عدم مطابقة', 'سلامة الغذاء', 'safety_nonconformance', 'insert'::change_strategy, '{}'::text[], array['source', 'severity', 'description', 'immediate_action', 'due_date', 'raised_by', 'raised_by_name']::text[], array['executive'::staff_role, 'kitchen'::staff_role, 'quality'::staff_role], 'executive'::staff_role, false, 'بلاغ عدم مطابقة جديد — واقعة تُسجَّل فوراً، ما تمر بمسار الاعتماد'),
  ('ncr.update', 'معالجة عدم مطابقة', 'سلامة الغذاء', 'safety_nonconformance', 'upsert'::change_strategy, array['id']::text[], array['status', 'root_cause', 'corrective_action', 'preventive_action', 'due_date', 'closed_by', 'closed_by_name', 'closed_at']::text[], array['quality'::staff_role, 'executive'::staff_role], 'executive'::staff_role, true, 'السبب الجذري والإجراءات وإغلاق البلاغ'),
  ('haccp_step.set', 'خطوة في خطة HACCP', 'سلامة الغذاء', 'safety_haccp_steps', 'upsert'::change_strategy, array['step_index']::text[], array['label', 'stage', 'hazard', 'hazard_type', 'control_measure', 'is_ccp', 'ccp_code', 'active', 'note']::text[], array['quality'::staff_role], 'executive'::staff_role, true, 'خطوة في الخطة ونوع خطرها'),
  ('limit.set', 'حد حرج', 'سلامة الغذاء', 'safety_critical_limits', 'upsert'::change_strategy, array['id']::text[], array['step_index', 'parameter', 'limit_kind', 'min_value', 'max_value', 'unit', 'monitoring_method', 'frequency', 'corrective_action', 'active', 'sort_order']::text[], array['quality'::staff_role], 'executive'::staff_role, true, 'حدود نقطة التحكّم وطريقة مراقبتها'),
  ('limit.add', 'حد حرج جديد', 'سلامة الغذاء', 'safety_critical_limits', 'insert'::change_strategy, '{}'::text[], array['step_index', 'parameter', 'limit_kind', 'min_value', 'max_value', 'unit', 'monitoring_method', 'frequency', 'corrective_action', 'sort_order']::text[], array['quality'::staff_role], 'executive'::staff_role, true, 'إضافة حد حرج لنقطة تحكّم'),
  ('iso.set', 'بند ISO 22000', 'سلامة الغذاء', 'safety_iso_clauses', 'upsert'::change_strategy, array['clause']::text[], array['status', 'evidence', 'owner_role', 'updated_by']::text[], array['quality'::staff_role], 'executive'::staff_role, true, 'حالة بند من بنود المواصفة ودليلها'),
  ('staff.set', 'عضو فريق', 'الفريق', 'staff', 'upsert'::change_strategy, array['user_id']::text[], array['role', 'name', 'active']::text[], array['executive'::staff_role], 'executive'::staff_role, false, 'دور الموظف واسمه وتفعيله — واقعة تُسجَّل فوراً، ما تمر بمسار الاعتماد')
on conflict (kind) do nothing;

-- خطة HACCP: 8 خطوة (قيم بداية — لا تُكتب فوق الموجود)
insert into safety_haccp_steps (step_index, label, stage, hazard, hazard_type, control_measure, is_ccp, ccp_code) values
  (1, 'استلام المواد', 'استلام', 'وصول مواد خارج نطاق الحرارة الآمن أو من مورد غير معتمد', 'biological', 'فحص حرارة الشحنة والتاريخ والمورد عند الاستلام', true, 'CCP1'),
  (2, 'التخزين البارد', 'تخزين', 'نمو الممرضات عند ارتفاع حرارة الثلاجة', 'biological', 'مراقبة حرارة الثلاجة والفريزر كل وردية', true, 'CCP2'),
  (3, 'التخزين الجاف', 'تخزين', 'آفات ورطوبة وتلوث مواد كيميائية', 'physical', 'فصل المواد الكيميائية، رفع عن الأرض، ومكافحة آفات', false, ''),
  (4, 'التحضير والتقطيع', 'تحضير', 'تلوث متقاطع بين المواد النيئة والجاهزة ومسببات الحساسية', 'allergen', 'ألواح وأدوات مفصولة بالألوان، وغسل أيدٍ بين المهام', false, ''),
  (5, 'الطبخ', 'طبخ', 'بقاء ممرضات حية لعدم بلوغ حرارة القلب', 'biological', 'قياس حرارة قلب المنتج بميزان مسبار معاير', true, 'CCP3'),
  (6, 'التبريد بعد الطبخ', 'تبريد', 'تكاثر الممرضات في نطاق الخطر أثناء التبريد البطيء', 'biological', 'تبريد سريع ضمن زمن محدد وتسجيل الحرارة', true, 'CCP4'),
  (7, 'التغليف والملصق', 'تسليم', 'ملصق لا يطابق المحتوى أو ناقص بيان مسببات الحساسية', 'allergen', 'مطابقة الملصق مع الوصفة المعتمدة قبل الإغلاق', true, 'CCP5'),
  (8, 'النقل والتسليم', 'تسليم', 'انقطاع سلسلة التبريد أثناء التوصيل', 'biological', 'حافظات معزولة وقياس حرارة عند المغادرة', true, 'CCP6')
on conflict (step_index) do nothing;

-- 10 حد حرج
insert into safety_critical_limits (step_index, parameter, limit_kind, min_value, max_value, unit, monitoring_method, frequency, corrective_action, sort_order)
select v.* from (values
  (1, 'حرارة الشحنة المبردة عند الاستلام', 'numeric', null, 5, '°م', 'ميزان مسبار على عينة من الشحنة', 'كل شحنة', 'رفض الشحنة وتوثيق البلاغ للمورد', 0),
  (1, 'حرارة الشحنة المجمدة عند الاستلام', 'numeric', null, -15, '°م', 'ميزان مسبار على عينة من الشحنة', 'كل شحنة', 'رفض الشحنة وتوثيق البلاغ للمورد', 1),
  (1, 'المورد معتمد والشحنة بتاريخ سارٍ', 'boolean', null, null, '', 'مطابقة مع قائمة الموردين المعتمدين', 'كل شحنة', 'رفض الشحنة وعدم إدخالها المخزن', 2),
  (2, 'حرارة الثلاجة', 'numeric', 1, 5, '°م', 'ميزان الثلاجة المعاير', 'كل وردية', 'نقل المواد لثلاجة سليمة، تقييم صلاحية المواد، وإصلاح الوحدة', 3),
  (2, 'حرارة الفريزر', 'numeric', -22, -18, '°م', 'ميزان الفريزر المعاير', 'كل وردية', 'نقل المواد لفريزر سليم، تقييم المواد، وإصلاح الوحدة', 4),
  (5, 'حرارة قلب المنتج بعد الطبخ', 'numeric', 74, null, '°م', 'ميزان مسبار في أسمك جزء', 'كل دفعة', 'إعادة الطبخ حتى بلوغ الحد وإعادة القياس', 5),
  (6, 'زمن التبريد من 60°م إلى 21°م', 'numeric', null, 2, 'ساعة', 'قياس بالساعة والميزان', 'كل دفعة', 'إتلاف الدفعة إذا تجاوز الزمن', 6),
  (6, 'زمن التبريد من 21°م إلى 5°م', 'numeric', null, 4, 'ساعة', 'قياس بالساعة والميزان', 'كل دفعة', 'إتلاف الدفعة إذا تجاوز الزمن', 7),
  (7, 'الملصق يطابق الوصفة ومسببات حساسيتها', 'boolean', null, null, '', 'مطابقة بصرية مع بطاقة الصنف المعتمدة', 'كل دفعة', 'إيقاف التغليف وإعادة طباعة الملصق', 8),
  (8, 'حرارة الوجبة عند مغادرة المطبخ', 'numeric', null, 5, '°م', 'ميزان مسبار على عينة من الطلبية', 'كل رحلة توصيل', 'إرجاع الطلبية وتقييم صلاحيتها قبل أي تسليم', 9)
) as v(step_index, parameter, limit_kind, min_value, max_value, unit, monitoring_method, frequency, corrective_action, sort_order)
where not exists (select 1 from safety_critical_limits x
  where x.step_index = v.step_index and x.parameter = v.parameter);

-- 17 برنامج متطلبات أساسية
insert into safety_prp_programs (code, label, category, owner_role, frequency, sort_order) values
  ('PRP-01', 'نظافة الأسطح وأدوات التحضير', 'نظافة', 'kitchen'::staff_role, 'يومي', 0),
  ('PRP-02', 'نظافة الأرضيات والمصارف', 'نظافة', 'kitchen'::staff_role, 'يومي', 1),
  ('PRP-03', 'نظافة الثلاجات والفريزرات من الداخل', 'نظافة', 'kitchen'::staff_role, 'أسبوعي', 2),
  ('PRP-04', 'غسل الأيدي والصحة الشخصية', 'نظافة', 'kitchen'::staff_role, 'كل وردية', 3),
  ('PRP-05', 'ملابس العمل وأغطية الرأس والقفازات', 'نظافة', 'kitchen'::staff_role, 'كل وردية', 4),
  ('PRP-06', 'مكافحة الآفات: فحص المصائد ونقاط الدخول', 'مكافحة آفات', 'quality'::staff_role, 'أسبوعي', 5),
  ('PRP-07', 'زيارة شركة مكافحة الآفات المتعاقدة', 'مكافحة آفات', 'quality'::staff_role, 'شهري', 6),
  ('PRP-08', 'معايرة موازين الحرارة', 'صيانة', 'quality'::staff_role, 'شهري', 7),
  ('PRP-09', 'صيانة وحدات التبريد الوقائية', 'صيانة', 'kitchen'::staff_role, 'ربع سنوي', 8),
  ('PRP-10', 'فحص صلاحية مياه الشرب والثلج', 'صيانة', 'quality'::staff_role, 'ربع سنوي', 9),
  ('PRP-11', 'فصل النفايات وإخراجها', 'نظافة', 'kitchen'::staff_role, 'يومي', 10),
  ('PRP-12', 'تخزين المواد الكيميائية بعيداً عن الغذاء', 'تخزين', 'kitchen'::staff_role, 'أسبوعي', 11),
  ('PRP-13', 'فحص صلاحية مواد المخزن ومبدأ FIFO', 'تخزين', 'kitchen'::staff_role, 'يومي', 12),
  ('PRP-14', 'تدريب سلامة الغذاء للموظفين الجدد', 'تدريب', 'quality'::staff_role, 'عند التعيين', 13),
  ('PRP-15', 'تجديد الشهادات الصحية للموظفين', 'تدريب', 'executive'::staff_role, 'سنوي', 14),
  ('PRP-16', 'تقييم الموردين وتجديد شهاداتهم', 'موردون', 'quality'::staff_role, 'سنوي', 15),
  ('PRP-17', 'تتبّع الدفعات واختبار الاستدعاء', 'تتبّع', 'quality'::staff_role, 'نصف سنوي', 16)
on conflict (code) do nothing;

-- 30 بند ISO 22000
insert into safety_iso_clauses (clause, title, owner_role, sort_order) values
  ('4.1', 'فهم المنشأة وسياقها', 'executive'::staff_role, 0),
  ('4.2', 'فهم احتياجات الأطراف المعنية وتوقعاتها', 'executive'::staff_role, 1),
  ('4.3', 'تحديد نطاق نظام إدارة سلامة الغذاء', 'executive'::staff_role, 2),
  ('4.4', 'نظام إدارة سلامة الغذاء وعملياته', 'quality'::staff_role, 3),
  ('5.1', 'القيادة والالتزام', 'executive'::staff_role, 4),
  ('5.2', 'سياسة سلامة الغذاء', 'executive'::staff_role, 5),
  ('5.3', 'الأدوار والمسؤوليات والصلاحيات', 'executive'::staff_role, 6),
  ('6.1', 'إجراءات معالجة المخاطر والفرص', 'quality'::staff_role, 7),
  ('6.2', 'أهداف سلامة الغذاء والتخطيط لبلوغها', 'executive'::staff_role, 8),
  ('6.3', 'تخطيط التغييرات', 'quality'::staff_role, 9),
  ('7.1', 'الموارد: الأفراد والبنية والبيئة', 'executive'::staff_role, 10),
  ('7.2', 'الكفاءة', 'quality'::staff_role, 11),
  ('7.3', 'التوعية', 'quality'::staff_role, 12),
  ('7.4', 'التواصل الداخلي والخارجي', 'quality'::staff_role, 13),
  ('7.5', 'المعلومات الموثّقة', 'quality'::staff_role, 14),
  ('8.1', 'التخطيط والضبط التشغيلي', 'quality'::staff_role, 15),
  ('8.2', 'برامج المتطلبات الأساسية PRP', 'quality'::staff_role, 16),
  ('8.3', 'نظام التتبّع', 'quality'::staff_role, 17),
  ('8.4', 'التأهب للطوارئ والاستجابة', 'executive'::staff_role, 18),
  ('8.5', 'ضبط المخاطر: تحليل الأخطار وخطة HACCP', 'quality'::staff_role, 19),
  ('8.6', 'تحديث معلومات PRP وخطة الضبط', 'quality'::staff_role, 20),
  ('8.7', 'ضبط المراقبة والقياس (المعايرة)', 'quality'::staff_role, 21),
  ('8.8', 'التحقق من PRP وخطة الضبط', 'quality'::staff_role, 22),
  ('8.9', 'ضبط عدم المطابقة: التصحيح والسحب والاستدعاء', 'quality'::staff_role, 23),
  ('9.1', 'المراقبة والقياس والتحليل والتقييم', 'quality'::staff_role, 24),
  ('9.2', 'التدقيق الداخلي', 'quality'::staff_role, 25),
  ('9.3', 'مراجعة الإدارة', 'executive'::staff_role, 26),
  ('10.1', 'عدم المطابقة والإجراء التصحيحي', 'quality'::staff_role, 27),
  ('10.2', 'التحسين المستمر', 'executive'::staff_role, 28),
  ('10.3', 'تحديث نظام إدارة سلامة الغذاء', 'quality'::staff_role, 29)
on conflict (clause) do nothing;

-- إعدادات الحصص والتكلفة والتسعير
insert into ops_settings (id, data) values (1, '{"multipliers": {"P": {"lean": 1, "balanced": 1, "performance": 1.3}, "C": {"lean": 0.6, "balanced": 1, "performance": 1.45}, "V": {"lean": 1.25, "balanced": 1, "performance": 1}, "S": {"lean": 0.75, "balanced": 1, "performance": 1.15}}, "sections": {"رئيسي": {"packaging": 3, "targetCostPct": 0.33, "labor": 4}, "فطور": {"packaging": 2.2, "targetCostPct": 0.3, "labor": 3}, "سناك": {"packaging": 1.2, "targetCostPct": 0.3, "labor": 1.5}, "شوربة": {"packaging": 1.8, "targetCostPct": 0.28, "labor": 2}, "سلطة": {"packaging": 2.5, "targetCostPct": 0.32, "labor": 2.5}, "حلا": {"packaging": 1.5, "targetCostPct": 0.28, "labor": 2}}, "wastePct": 0.06, "spiceAllowance": 0.35, "priceRoundStep": 1, "lowCarbMax": 45, "highProteinMin": 30, "kcalDiffMax": 0.1, "vatRate": 0.15, "priceIncludesVat": 1, "paymentFeePct": 0.02, "appCommissionPct": 0.2, "appSalesShare": 0.3, "marginWarnPct": 0.25, "shelfLifeApprovalH": 72, "pilotPassesRequired": 3, "readyItemsRequired": 0}'::jsonb)
on conflict (id) do update set data = excluded.data;

-- مسميات الخانات وقواعدها
insert into ops_rotation_meta (id, slot_labels, slot_rule, day_labels, rules) values
  (1, array['فطور 1', 'فطور 2', 'فطور 3', 'فطور 4', 'غداء 1', 'غداء 2', 'غداء 3', 'غداء 4', 'عشاء 1', 'عشاء 2', 'عشاء 3', 'عشاء 4', 'سناك 1', 'سناك 2', 'سناك 3', 'سناك 4', 'شوربة 1', 'شوربة 2', 'سلطة 1', 'سلطة 2', 'حلا 1', 'حلا 2']::text[], array['فطور', 'فطور', 'فطور', 'فطور', 'دجاج', 'دجاج', 'لحم', 'سمك/ربيان', 'دجاج', 'دجاج', 'لحم', 'سمك/ربيان', 'سناك', 'سناك', 'سناك', 'سناك', 'شوربة', 'شوربة', 'سلطة', 'سلطة', 'حلا', 'حلا']::text[], array['1 · السبت', '2 · الأحد', '3 · الاثنين', '4 · الثلاثاء', '5 · الأربعاء', '6 · الخميس', '7 · الجمعة', '8 · السبت', '9 · الأحد', '10 · الاثنين', '11 · الثلاثاء', '12 · الأربعاء', '13 · الخميس', '14 · الجمعة']::text[], 'قواعد التوليد: لا يتكرر صنف رئيسي في يومين متتاليين · كل يوم 3 أطباق خليجية/عربية على الأقل من 8 · غداء الجمعة فيه كبسة أو مجبوس أو مندي · لا صنف مكرر بين غداء وعشاء اليوم نفسه. قابل للتعديل يدوياً (غيّر النص ثم راجع أعمدة الفحص).')
on conflict (id) do update set
  slot_labels = excluded.slot_labels, slot_rule = excluded.slot_rule,
  day_labels = excluded.day_labels, rules = excluded.rules;

-- جدول الدوران: 14 يوم × 22 خانة = 308 خانة
insert into ops_rotation (day_index, slot, sku) values
  (0, 0, 'B06'),
  (0, 1, 'B07'),
  (0, 2, 'B08'),
  (0, 3, 'B03'),
  (0, 4, 'C04'),
  (0, 5, 'C02'),
  (0, 6, 'M06'),
  (0, 7, 'F02'),
  (0, 8, 'C08'),
  (0, 9, 'C05'),
  (0, 10, 'M01'),
  (0, 11, 'F03'),
  (0, 12, 'S06'),
  (0, 13, 'S01'),
  (0, 14, 'S05'),
  (0, 15, 'S08'),
  (0, 16, 'SP02'),
  (0, 17, 'SP04'),
  (0, 18, 'SL04'),
  (0, 19, 'SL03'),
  (0, 20, 'D03'),
  (0, 21, 'D02'),
  (1, 0, 'B01'),
  (1, 1, 'B02'),
  (1, 2, 'B03'),
  (1, 3, 'B04'),
  (1, 4, 'C03'),
  (1, 5, 'C06'),
  (1, 6, 'M02'),
  (1, 7, 'F05'),
  (1, 8, 'C11'),
  (1, 9, 'C01'),
  (1, 10, 'M03'),
  (1, 11, 'F04'),
  (1, 12, 'S07'),
  (1, 13, 'S04'),
  (1, 14, 'S05'),
  (1, 15, 'S02'),
  (1, 16, 'SP01'),
  (1, 17, 'SP03'),
  (1, 18, 'SL05'),
  (1, 19, 'SL02'),
  (1, 20, 'D04'),
  (1, 21, 'D01'),
  (2, 0, 'B03'),
  (2, 1, 'B07'),
  (2, 2, 'B08'),
  (2, 3, 'B06'),
  (2, 4, 'C09'),
  (2, 5, 'C12'),
  (2, 6, 'M01'),
  (2, 7, 'F01'),
  (2, 8, 'C10'),
  (2, 9, 'C07'),
  (2, 10, 'M04'),
  (2, 11, 'F06'),
  (2, 12, 'S08'),
  (2, 13, 'S06'),
  (2, 14, 'S03'),
  (2, 15, 'S01'),
  (2, 16, 'SP02'),
  (2, 17, 'SP04'),
  (2, 18, 'SL01'),
  (2, 19, 'SL04'),
  (2, 20, 'D03'),
  (2, 21, 'D02'),
  (3, 0, 'B07'),
  (3, 1, 'B02'),
  (3, 2, 'B04'),
  (3, 3, 'B06'),
  (3, 4, 'C04'),
  (3, 5, 'C05'),
  (3, 6, 'M05'),
  (3, 7, 'F02'),
  (3, 8, 'C02'),
  (3, 9, 'C08'),
  (3, 10, 'M06'),
  (3, 11, 'F03'),
  (3, 12, 'S07'),
  (3, 13, 'S08'),
  (3, 14, 'S02'),
  (3, 15, 'S06'),
  (3, 16, 'SP01'),
  (3, 17, 'SP03'),
  (3, 18, 'SL02'),
  (3, 19, 'SL05'),
  (3, 20, 'D01'),
  (3, 21, 'D04'),
  (4, 0, 'B03'),
  (4, 1, 'B08'),
  (4, 2, 'B04'),
  (4, 3, 'B06'),
  (4, 4, 'C01'),
  (4, 5, 'C06'),
  (4, 6, 'M03'),
  (4, 7, 'F05'),
  (4, 8, 'C03'),
  (4, 9, 'C11'),
  (4, 10, 'M02'),
  (4, 11, 'F04'),
  (4, 12, 'S04'),
  (4, 13, 'S08'),
  (4, 14, 'S02'),
  (4, 15, 'S01'),
  (4, 16, 'SP04'),
  (4, 17, 'SP02'),
  (4, 18, 'SL01'),
  (4, 19, 'SL03'),
  (4, 20, 'D03'),
  (4, 21, 'D02'),
  (5, 0, 'B02'),
  (5, 1, 'B05'),
  (5, 2, 'B03'),
  (5, 3, 'B06'),
  (5, 4, 'C12'),
  (5, 5, 'C10'),
  (5, 6, 'M04'),
  (5, 7, 'F01'),
  (5, 8, 'C07'),
  (5, 9, 'C09'),
  (5, 10, 'M01'),
  (5, 11, 'F06'),
  (5, 12, 'S03'),
  (5, 13, 'S07'),
  (5, 14, 'S02'),
  (5, 15, 'S05'),
  (5, 16, 'SP03'),
  (5, 17, 'SP01'),
  (5, 18, 'SL05'),
  (5, 19, 'SL02'),
  (5, 20, 'D01'),
  (5, 21, 'D04'),
  (6, 0, 'B03'),
  (6, 1, 'B07'),
  (6, 2, 'B05'),
  (6, 3, 'B04'),
  (6, 4, 'C08'),
  (6, 5, 'C02'),
  (6, 6, 'M05'),
  (6, 7, 'F03'),
  (6, 8, 'C04'),
  (6, 9, 'C05'),
  (6, 10, 'M06'),
  (6, 11, 'F02'),
  (6, 12, 'S06'),
  (6, 13, 'S01'),
  (6, 14, 'S03'),
  (6, 15, 'S04'),
  (6, 16, 'SP02'),
  (6, 17, 'SP04'),
  (6, 18, 'SL01'),
  (6, 19, 'SL03'),
  (6, 20, 'D02'),
  (6, 21, 'D03'),
  (7, 0, 'B01'),
  (7, 1, 'B06'),
  (7, 2, 'B05'),
  (7, 3, 'B08'),
  (7, 4, 'C06'),
  (7, 5, 'C11'),
  (7, 6, 'M03'),
  (7, 7, 'F04'),
  (7, 8, 'C01'),
  (7, 9, 'C03'),
  (7, 10, 'M02'),
  (7, 11, 'F05'),
  (7, 12, 'S08'),
  (7, 13, 'S02'),
  (7, 14, 'S04'),
  (7, 15, 'S03'),
  (7, 16, 'SP03'),
  (7, 17, 'SP01'),
  (7, 18, 'SL04'),
  (7, 19, 'SL05'),
  (7, 20, 'D01'),
  (7, 21, 'D04'),
  (8, 0, 'B02'),
  (8, 1, 'B04'),
  (8, 2, 'B01'),
  (8, 3, 'B07'),
  (8, 4, 'C07'),
  (8, 5, 'C10'),
  (8, 6, 'M04'),
  (8, 7, 'F01'),
  (8, 8, 'C12'),
  (8, 9, 'C09'),
  (8, 10, 'M01'),
  (8, 11, 'F06'),
  (8, 12, 'S04'),
  (8, 13, 'S03'),
  (8, 14, 'S06'),
  (8, 15, 'S01'),
  (8, 16, 'SP02'),
  (8, 17, 'SP04'),
  (8, 18, 'SL01'),
  (8, 19, 'SL02'),
  (8, 20, 'D03'),
  (8, 21, 'D02'),
  (9, 0, 'B01'),
  (9, 1, 'B05'),
  (9, 2, 'B08'),
  (9, 3, 'B02'),
  (9, 4, 'C08'),
  (9, 5, 'C04'),
  (9, 6, 'M06'),
  (9, 7, 'F02'),
  (9, 8, 'C02'),
  (9, 9, 'C05'),
  (9, 10, 'M05'),
  (9, 11, 'F03'),
  (9, 12, 'S06'),
  (9, 13, 'S02'),
  (9, 14, 'S08'),
  (9, 15, 'S05'),
  (9, 16, 'SP01'),
  (9, 17, 'SP03'),
  (9, 18, 'SL03'),
  (9, 19, 'SL05'),
  (9, 20, 'D01'),
  (9, 21, 'D04'),
  (10, 0, 'B02'),
  (10, 1, 'B01'),
  (10, 2, 'B07'),
  (10, 3, 'B03'),
  (10, 4, 'C01'),
  (10, 5, 'C11'),
  (10, 6, 'M02'),
  (10, 7, 'F05'),
  (10, 8, 'C06'),
  (10, 9, 'C03'),
  (10, 10, 'M03'),
  (10, 11, 'F04'),
  (10, 12, 'S06'),
  (10, 13, 'S03'),
  (10, 14, 'S07'),
  (10, 15, 'S05'),
  (10, 16, 'SP04'),
  (10, 17, 'SP02'),
  (10, 18, 'SL04'),
  (10, 19, 'SL02'),
  (10, 20, 'D02'),
  (10, 21, 'D03'),
  (11, 0, 'B05'),
  (11, 1, 'B08'),
  (11, 2, 'B02'),
  (11, 3, 'B04'),
  (11, 4, 'C12'),
  (11, 5, 'C07'),
  (11, 6, 'M04'),
  (11, 7, 'F01'),
  (11, 8, 'C09'),
  (11, 9, 'C10'),
  (11, 10, 'M01'),
  (11, 11, 'F06'),
  (11, 12, 'S07'),
  (11, 13, 'S01'),
  (11, 14, 'S05'),
  (11, 15, 'S02'),
  (11, 16, 'SP03'),
  (11, 17, 'SP01'),
  (11, 18, 'SL03'),
  (11, 19, 'SL01'),
  (11, 20, 'D04'),
  (11, 21, 'D01'),
  (12, 0, 'B08'),
  (12, 1, 'B06'),
  (12, 2, 'B05'),
  (12, 3, 'B01'),
  (12, 4, 'C04'),
  (12, 5, 'C05'),
  (12, 6, 'M06'),
  (12, 7, 'F03'),
  (12, 8, 'C08'),
  (12, 9, 'C02'),
  (12, 10, 'M05'),
  (12, 11, 'F02'),
  (12, 12, 'S04'),
  (12, 13, 'S07'),
  (12, 14, 'S03'),
  (12, 15, 'S01'),
  (12, 16, 'SP04'),
  (12, 17, 'SP02'),
  (12, 18, 'SL04'),
  (12, 19, 'SL02'),
  (12, 20, 'D02'),
  (12, 21, 'D03'),
  (13, 0, 'B04'),
  (13, 1, 'B05'),
  (13, 2, 'B07'),
  (13, 3, 'B01'),
  (13, 4, 'C03'),
  (13, 5, 'C01'),
  (13, 6, 'M02'),
  (13, 7, 'F05'),
  (13, 8, 'C06'),
  (13, 9, 'C12'),
  (13, 10, 'M03'),
  (13, 11, 'F04'),
  (13, 12, 'S07'),
  (13, 13, 'S04'),
  (13, 14, 'S05'),
  (13, 15, 'S08'),
  (13, 16, 'SP03'),
  (13, 17, 'SP01'),
  (13, 18, 'SL03'),
  (13, 19, 'SL01'),
  (13, 20, 'D01'),
  (13, 21, 'D04')
on conflict (day_index, slot) do update set sku = excluded.sku;

commit;

-- تحقق سريع بعد التنفيذ:
--   select count(*) from ops_ingredients;   -- المتوقع 80
--   select count(*) from ops_menu_items;    -- المتوقع 53
--   select count(*) from ops_recipe_lines;  -- المتوقع 457
--   select count(*) from ops_rotation;      -- المتوقع 308
--   select count(*) from ops_gate_defs;     -- المتوقع 8
--   select count(*) from ops_launch_axes;   -- المتوقع 5
--   select count(*) from ops_change_kinds;  -- المتوقع 25
--   select count(*) from safety_critical_limits; -- المتوقع 10
